default.nix, modules/services/emacs.nix
Adds an expression (compatible w/ linux counterpart) for starting emacs daemon as a launchd service.
=> adds emacs launchd service

modules/programs/zsh/default.nix
Awesome project!
I added an option for zsh to enable zsh-syntax-highlighting. Mostly copied from the nixos zsh.nix https://github.com/NixOS/nixpkgs/blob/05a4fbd56d68ea88a190906f4bcd2bfc97a4c8e4/nixos/modules/programs/zsh/zsh.nix
=> Added zsh-syntax-highlighting option to zsh program

README.md
Make a few nitpicky spelling and wording changes to `README.md`. Also, delete one instance of trailing whitespace.
=> Nitpick README.md

default.nix, modules/services/mopidy.nix
Basic support for mopidy service along with media keys support service.
Currently the mopidy installation via nix is broken, therefore set the default packages to `/usr/local`.
Have a look if that's something you're ok with including :)
=> Adds mopidy service with media keys support

modules/services/mopidy.nix
Noticed that adaptive service causes mopidy to stutter under heavy load. 
Mediakeys though works fine as adaptive.
=> Makes mopidy service interactive

modules/environment/default.nix
If you don't include "man", basic nix commands (e.g. nix-env) basically have broken help/usage text, since they delegate to calling man.
=> Default outputs should include "man"

pkgs/nix-tools/darwin-option.sh
There isn't a man page and it's useful to print out the list of top-level keys.
=> Better no-args darwin-options output

modules/environment/default.nix
Your user-specific profile should take precedence over the system one. If I've gone out of my way to install something into my personal profile, my version should be used instead of the system's.
=> Don't put profiles in reverse-order in PATH

default.nix, modules/services/chunkwm.nix
As KWM is now deprecated and ChunkWM is the thing to follow, I made myself a module for configuring it. 
The quirk however is that as of now [ChunkWM does not support custom config path](https://github.com/koekeishiya/chunkwm/issues/96), hence you either need to:
- make `/etc/{chunkwmrc,chunkwmtilingrc}` executable and symlink `/etc/{chunkwmrc,chunkwmtilingrc}` as $HOME dotfiles
- create executable wrappers in $HOME sourcing the above (as I'm using stow to manage dotfiles that's what I do for now)
Sidenote: I also do have ugly derivations for installing ChunkWM and plugins if you're interested
=> Adds support for ChunkWM

modules/services/emacs.nix
The motivation of the change is that some forks (ie. Wilfred/remacs)
choose not to use the emacs binary. Whereas it is perfectly possible
to generate /bin/emacs in a drv, but I strongly believe it's cleaner
to have a service parameter.
=> Adds service.emacs.exec to choose emacs binary to execute

modules/system/applications.nix
This allows you to easily browse and spotlight-search Nix apps without having to give your entire `~/Applications` over to Nix.
=> Make symlink within ~/Applications if it exists instead of skipping

bootstrap.sh
Also, only `echo` that the example configuration is being copied when it’s
actually being copied.
=> Use the correct path for the darwin channel when bootstrapping.

modules/system/defaults-write.nix, modules/system/defaults/default.nix, modules/system/defaults/trackpad.nix
- Write trackpad settings to both `com.apple.AppleMultitouchTrackpad` and `com.apple.driver.AppleBluetoothMultitouch.trackpad` (seems necessary for Sierra+)
- Add `TrackpadThreeFingerDrag` setting to trackpad module
=> Improve trackpad settings support

modules/environment/default.nix, modules/programs/fish.nix, tests/system-path-fish.nix
This PR essentially replaces this file with the nixos fish module. The only difference between the two now is nuking the reference to `environment.shells`  🎉 
The NixOS fish module has a number of nice features that we're gaining, such as more customizable initialization.
=> Port over the NixOS fish module

modules/programs/tmux.nix
**N.B. This is quick, dirty and untested. Feel free to amend as appropriate.**
That is, don't use `reattach-to-user-namespace`. iTerm2 provides [an option](https://iterm2.com/documentation-preferences.html) to allow applications in the terminal to access the clipboard, as well as deeper [shell integration utilities](https://iterm2.com/documentation-utilities.html), which obviate the need for `reattach-to-user-namespace`. What's more, iTerm2's [tmux integration](https://iterm2.com/documentation-tmux-integration.html) doesn't work with it, [nor when `aggressive-resize` is `on`](https://github.com/tmux-plugins/tmux-sensible/issues/24).
Currently, I'm avoiding the issues by including the following in [my `darwin-configuration.nix`](https://github.com/yurrriq/dotfiles/blob/ef83f1f1e56d4000ff442 …
=> tmux: play nice with iTerm2

default.nix, modules/services/buildkite-agent.nix, release.nix, tests/buildkite-agent.nix
This module lets you use your Mac as a build slave for the Buildkite CI system.
The `buildkite-agent` package used will need to come from the unstable channel.
=> Add buildkite-agent module

default.nix, modules/examples/lnl.nix, modules/system/defaults-write.nix, modules/system/defaults/screencapture.nix
Very simple - I don't like cluttering my desktop 😉   
Tested and works like a charm: `defaults read com.apple.screencapture location` after customising it and rebuilding shows the new value. And, fortunately, works immediately: new screenshots go to the new specified location, without the need of a `killall SystemUIServer` (as some articles on the web would suggest is necessary).
=> defaults: Add screencapture.location

default.nix, modules/services/skhd/default.nix
This adds [koekeishiya/skhd](https://github.com/koekeishiya/skhd) module. An alternative to already existing [khd](../tree/master/modules/services/khd) one that promises (and delivers) significant speedup. Currently we're not providing a default configuration for khd hence there is no default for skhd.
=> adds skhd module

modules/services/buildkite-agent.nix, tests/services-buildkite-agent.nix
Here are two fixes for buildkite-agent.
1. Port a shell quoting fix from NixOS/nixpkgs#38326
2. The daemon was starting before the hostname was set, which caused it to register itself as "localhost". This adds a fix for that.
Cheers
=> buildkite-agent fixes

default.nix, modules/programs/gnupg.nix
Add
```
programs.gnupg.agent.enable = true;
programs.gnupg.agent.enableSSHSupport = true;
```
to your config to get `gpg-agent` with SSH support.
Without `enableSSHSupport` this doesn’t really do anything, because, well, with the current design of GnuPG the agent is spawned automatically when needed.  So this whole thing is really only useful for ssh.
I tried to make it socket-activated, but `gpg-agent` only supports systemd-style socket activation. I think, theoretically, it should be possible to have a wrapper that will make systemd-style activated servers compatible with launchd, but I couldn’t figure our the launchd activation protocol :/.
Closes #77.
=> gnupg: add gpg-agent service

default.nix, modules/services/mail/offlineimap.nix, release.nix, tests/services-offlineimap.nix
This PR provides a basic service module for `offlineimap`. Offlineimap can be heavily configured by cli parameters as well as through an rc file. The service module offers only basic startup options and lets the rest of the configuration to be done through an run control script `.offlineimaprc`, because account management and credentials are beyond the scope of nix-darwin afaik.
~**Disclaimer:** The tests and some local smoke tests are passing for this PR. However, i am away from one of my machines, where i make use of offlineimap. I can cover this by the end of June.~
=> Init offlineimap service

pkgs/darwin-installer/default.nix
This is needed for the case when the user already has their config on `NIX_PATH` but has no working Nix. (🤷‍♀️ Things happen!)
=> installer: Bring our own `nix-instantiate`

modules/services/skhd/default.nix
This can be overrided if necessary, but I don't see any reason the nixpkgs package shouldn't be the default. It looks like this package didn't exist when the service was created.
=> Make the skhd service default to the skhd package

pkgs/nix-tools/darwin-rebuild.sh
As a user I don't want to remember where the configuration exists. This
adds a command that will point the $EDITOR to the <darwin-config> file.
darwin-rebuild edit
=> darwin-rebuild edit

pkgs/darwin-installer/configuration.nix, pkgs/darwin-installer/default.nix, pkgs/darwin-uninstaller/configuration.nix
Using a nix 2.1 nix-channel/nix-env with a 2.0 nix-daemon doesn't work
because the buildenv implementation was moved to the daemon.  This means
the nix version of the target darwin system can't be used because the
daemon isn't upgraded yet.
error: unsupported builtin function 'buildenv'
=> installer: prefer nix from default profile

README.md, default.nix, modules/fonts/default.nix, modules/system/activation-scripts.nix, release.nix, tests/fonts.nix
Adds a `fonts` module that once enabled (`enableFontDir`) takes fonts under nix management. Supports both `.ttf` and `.otf` fonts available in nixpkgs.
The effect is the fonts are *hardlinked* (symlinks do not work with darwin's way of loading fonts) into `/Library/Fonts` and cleaned-up and relinked upon rebuild. Manually copied fonts will be removed unless `enableFontDir` is set to false again.
Sample config:
```
fonts = {
enableFontDir = true;
fonts = [ pkgs.dejavu_fonts ];
};
```
Effect:
```
ls -l /Library/Fonts | grep Prag
-r--r--r--    2 root 1.5M Jan  1  1970 FSD - PragmataPro-Bold.ttf
-r--r--r--    2 root 1.4M Jan  1  1970 FSD - PragmataPro-BoldItalic.ttf
-r--r--r--    2 root 1.4M Jan  1  1970 FSD - PragmataPro-Italic.ttf
-r--r--r--    2 root 2.0M Jan  1  1970 FSD - PragmataPro.ttf …
```
=> initialise fonts module

modules/system/defaults/dock.nix
New option introduced in Mojave.
=> system.defaults.dock: add `show-recents` option

modules/services/emacs.nix
As the default package is now emacs 26.1 and --daemon flag falls back to forking behaviour the recommended way is to use fg-daemon, see: https://lists.gnu.org/archive/html/emacs-devel/2016-11/msg00383.html, https://lists.gnu.org/archive/html/emacs-devel/2017-05/msg00861.html
=> [services.emacs] use `fg-daemon` flag for service

modules/programs/zsh/default.nix
This was added to NixOS in NixOS/nixpkgs@003cd41310b5b7839eb4c402d84dc25068026c3e, but apparently never got ported to nix-darwin.
This change makes, at least, `stack` and `git-annex` completions work for me.
=> zsh: Add vendor-completions to fpath

modules/fonts/default.nix, modules/system/default.nix, tests/fonts.nix
The new implementation is a bit smarter and only updates fonts that
changed.  But more importantly /run/current-system isn't used anymore
which breaks initial activation and installs the previous set of fonts
instead of the one in the new system.
Fixes #115
=> fonts: rewrite activation

modules/environment/default.nix, modules/users/default.nix, modules/users/user.nix, release.nix, tests/users-packages.nix
Nix darwin can now install user packages in a dedicated user-profile under `/etc/profiles/per-user/<name?>`.
=> users: install user packages via users.users.<name?>.packages

modules/services/postgresql/default.nix
Otherwise it fallbacks to `/bin/ln` which is outdated and might not work.
I'm in macOS 10.12 and this `ln` doesn't work
=> postgresql: Use core `ln` from coreutils

modules/services/postgresql/default.nix
`initdb` expects to read the locale or SQL_ASCII environment
variable to determine the most appropriate character set.
Instead, offer a configuration option.
Fixes https://github.com/LnL7/nix-darwin/issues/143
=> nix-darwin/postgresql: add character set config

modules/module-list.nix, modules/services/autossh.nix, release.nix, tests/autossh.nix
The options are identical, the only change is the use of `launchd.daemons` rather than the systemd configuration for starting sessions.  Well, that and `KeepAlive` is instructed to restart even on error exit, instead of just on success exit.  I'm not sure why you'd want to not restart on error.
It is working for me with [this config](https://github.com/eraserhd/dotfiles/blob/develop/macbook.nix#L23-L36).
=> port autossh service from nixos

modules/system/defaults/NSGlobalDomain.nix, tests/system-defaults-write.nix
Tested locally: When set to false, F11 adjusts volume; set to true, F11
reveals desktop.
=> Allow configuring external keyboard to use standard F-keys

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/GlobalPreferences.nix, tests/system-defaults-write.nix
Found in `System Preferences`->`Sound`->`Sound Effects`, the default is `Funk`.
I was missing this functionality. `.GlobalPreferences` has only been around since Sierra I believe, not sure if that matters. Also not sure if I should find more keys in this domain to make it a useful addition to nix-darwin?
I didn't verify that this works because I don't know how. Help in doing this would be appreciated.
=> Add defaults write for the alert sound

modules/services/autossh.nix, modules/services/hercules-ci-agent/default.nix, modules/services/postgresql/default.nix
nixpkgs recently properly deprecated `types.string`: https://github.com/NixOS/nixpkgs/pull/66346
=> modules: remove usages of types.string

bootstrap.sh
If the users do not already exist then installers who already have a configuration containing
```nix
{
services.nix-daemon.enable = false;
}
```
will not be able to complete an initial bootstrap on a clean machine. This is because the bootstrap script currently only creates users after an initial rebuild.
The users must exist before the rebuild is completed or the whole thing fails.
=> [bootstrap.sh] Moves build & rebuild to after user creation

modules/programs/tmux.nix
This change fixes #173.
This is necessary to allow shell sessions inside tmux having a chance to set environment properly.
=> tmux: clear __NIX_DARWIN_SET_ENVIRONMENT_DONE

modules/system/defaults/NSGlobalDomain.nix
Hey @LnL7 👋   
Wanted to set my menu bar to autohide on my system and figured I'd introduce an option to do it declaratively :)
Have tested locally on Catalina 10.15.2
Let me know if there's anything you want me to change!
=> defaults: introduce NSGlobalDomain option for "_HIHideMenuBar"

README.md
Original version leads to an error:
```
$(nix-build '<darwin>' -A system --no-out-link)/sw/bin/darwin-rebuild build
warning: Nix search path entry 'darwin-config=/Users/test/.nixpkgs/darwin-configuration.nix' does not exist, ignoring
error: file 'darwin-config' was not found in the Nix search path (add it using $NIX_PATH or -I), at /nix/store/z7469wjnpii0ybkfs2ny1lh4vw308n3k-darwin/darwin/default.nix:1:40
(use '--show-trace' to show detailed location information)
```
=> Fix path to darwin-config

modules/system/version.nix
A change of `commitIdFromGitRepo` in nixpkgs/lib/sources.nix
resulted in the error message
"attribute '.git' missing at nixpkgs/lib/sources.nix:7:32" when
executing darwin-rebuils switch.
The commit with the change is
https://github.com/NixOS/nixpkgs/commit/c9214c394b248e1f26e45dbe1be2bd82363af3a6
Removing the trailing slash resolves the error.
=> Remove trailing slash from path in commitIdFromGitRepo call

modules/services/buildkite-agent.nix
This adds a `services.buildkite-agent.preCommands` option. This is used to execute any commands you want to run directly before starting the buildkite agent.
=> buildkite: add preCommands option

modules/fonts/default.nix, tests/fonts.nix
On Catalina, the default way is to install Nix on a new volume which breaks hardlinking the font files. If that is the case I just copy them.
=> fonts: Adds support if Nix is on another filesystem.

modules/examples/lnl.nix, modules/programs/tmux.nix
The old option is still supported for now, but the user is warned.
=> Rename programs.tmux.tmuxConfig -> extraConfig

modules/launchd/default.nix, modules/services/nix-daemon.nix, release.nix, tests/services-activate-system-changed-label-prefix.nix, tests/services-nix-daemon.nix, tests/sockets-nix-daemon.nix
By adding this option, it allows multiple instances of nix-darwin to setup the machine.
At work, I'm adding nix-darwin as a submodule of our module system so we can install daemons for the user. However, it's not currently possible as it conflicts with the user installed nix-darwin.
=> launchd: allow customization of the default launchd prefix

modules/module-list.nix, modules/services/dnsmasq.nix, release.nix, tests/services-dnsmasq.nix
This is useful for redirecting some TLDs to the different addresses. For
example I use it to make all requests to `*.localhost` to be resolved to
loopback address which allows me to easily work and test services that
are relying on different domains.
=> Add DNSmasq service

.github/workflows/test.yml
Seems like this was renamed to macos-$version and macos-latest.
=> update macos label

modules/services/yabai/default.nix, tests/services-yabai.nix
If a user passes both `config` and `extraConfig` to the `yabai` serivce,
the generated `yabairc` file is invalid. This is because we do not add a
newline separator when we concatenate the config string generated by
`toYabaiConfig cfg.config` with `cfg.extraConfig`.
This PR prepends a newline to `cfg.extraConfig` if it is non-empty so
that the resulting `yabairc` config is valid.
@LnL7 @cmacrae could you please take a look? Let me know if I'm missing anything important. I tested this change locally and the generated `yabairc` is now correct.
=> Separate yabai config and extra config by newline

pkgs/darwin-installer/default.nix
I'm trying to bootstrap my machine from an existing config, which happens to be in a non-writable location. GNU `sed` doesn't like this and throws the following error:
```
sed: couldn't open temporary file /etc/macos/sedc9wviD: Permission denied
```
Would others agree it's reasonable to only run `sed` within the "config doesn't exist" branch?
Technically speaking this _could_ fail to enable `nix-daemon` on a multi-user install (by failing to un-comment the line) if the script failed between the calls to `cp` and `sed`, but that's a tiny window.
Another approach which wouldn't have that drawback would be to test that `$config` is writable before calling `sed`, however, I wanted to start with this solution because the spirit of the substitution is when the example config is first being …
=> Only enable `services.nix-daemon` when no config is present upon install

modules/examples/lnl.nix, modules/examples/ofborg.nix, modules/examples/simple.nix, modules/nix/default.nix
most users just want to use all available cores.
This commit aligns our defaults with what we do in NixOS
=> nix: better defaults settings for maxJobs/buildCores

modules/documentation/default.nix
This is safe to remove, because it is not referenced anywhere in
nix-darwin.
It should have been discovered way earlier, but a bug in the
module system has allowed this value to be defined until
https://github.com/NixOS/nixpkgs/commit/fd75dc876586bde8cdb683a6952a41132e8db166
=> documentation: Don't set localSystem which doesn't exist

default.nix, pkgs/darwin-installer/default.nix, pkgs/darwin-uninstaller/default.nix
This makes sure the `darwin-installer` and `darwin-uninstaller` packages can be nix copied to any target and reliably be executed there.
=> darwin-[un]installer: make sure all dependencies are part of the closure

modules/system/defaults/NSGlobalDomain.nix
This option does not take effect until the user logs out and then back in.  I didn't call this out because I think there are several options like this already.
I'm not sure Mac OS sets "Auto", but it isn't by setting this default.
=> Enable setting dark mode

modules/networking/default.nix, tests/networking-hostname.nix
I usually want my Mac's "computer name" to be different from its hostname. Currently this isn't possible with `nix-darwin` since setting `networking.hostname` changes all three of the hostname, local hostname and "computer name" to the same thing.
This PR makes the following changes:
* adds the options `networking.localHostName` and `networking.computerName`,
* Refines the types of `networking.HostName` to only accept strings that are valid hostnames and uses this type for `networking.localHostName` as well,
* changes the default behavior of setting `networking.hostname` to only set the system's hostname and local hostname (if the `networking.localHostName` option isn't set separately), and
* (This is done by having each option set the corresponding name for the system, and setting the …
=> Add separate options for ComputerName and LocalHostName in networking module

modules/launchd/launchd.nix, modules/programs/ssh/default.nix, modules/system/etc.nix, modules/system/launchd.nix, modules/users/default.nix
`types.loaOf` has been deprecated for a long time and is now in the process of removal. 
See: https://github.com/NixOS/nixpkgs/pull/96042
=> Remove deprecated types.loaOf

modules/system/keyboard.nix, tests/system-keyboard-mapping.nix
+ Tested with `darwin-rebuild switch -I darwin=.` in macOS Catalina.
+ Tested with `nix-build release.nix -A tests.system-keyboard-mapping`.
=> add new option - system.keyboard.swapLeftCommandAndLeftAlt

modules/services/redis/default.nix, release.nix, tests/services-redis.nix
👋 Hi, I tested this out with this bit from the README:
```sh
darwin-rebuild switch -I darwin=.
```
It worked on macOS Catalina with the following in my `~/.nixpkgs/darwin-configuration.nix`:
```nix
{
services.redis = {
enable = true;
extraConfig = ''
stop-writes-on-bgsave-error no
'';
};
}
```
I'm happy to run any additional tests if necessary, but I'm fairly new to Nix so I might need a little pointing in the right direction.
=> Add extraConfig option to Redis

modules/services/lorri.nix, tests/services-lorri.nix
When trying to use lorri, I kept getting errors similar to those mentioned by @wentasah on https://github.com/target/lorri/issues/385#issuecomment-661779666. I compared the relevant NixOS setting (shared by @curiousleo here https://github.com/target/lorri/issues/385#issuecomment-620477432) with the equivalent `darwin-nix` expression and I noticed that the one here lacked `git gnutar gzip`, so I added them.
=> add git, gnutar and gzip to lorri's path

modules/services/nextdns/default.nix
Adding the nextdns service.
I've tested by adding the corresponding launchd entry in my `darwin-configuration`. I don't know how to test the default.nix file.
It's pretty much taken from https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/nextdns.nix
just switching systemd to launchd
=> modules: add nextdns service

modules/system/shells.nix
I just installed the 10.15.7 upgrade, and noticed it replaced `/etc/shells` with a version that includes dash. I'm not sure which macOS release adds this, and if we should make this conditional somehow, or if this change matters at all.
=> Add /bin/dash to shells

modules/services/emacs.nix
Thanks for the help on this one!
Currently running the emacs daemon, will not set the path to the system path. So anything installed with nix won't be found (ripgrep, things for fancy git diffs...). This PR fixes that.
I've tested the fix by adding the same line in my `darwin-configuration.nix` file and it worked. Let me know if you want me to do something else.
I was running with the automated formatter on, so a couple of lines have changed formatting. It doesn't look like a bad thing, but let me know if it will be a problem.
closes #250 
I have question though. After using this, when I check the `getenv PATH` in emacs, I see `$HOME/.nix-profile/bin` however it looks like that  `$HOME` is hardcode and not properly replaced by it's value. I'm not sure how to fix that.
=> emacs: add system path env var

modules/services/yabai/default.nix
Big Sur brought some changes which requires yabai's scripting addition to be loaded by root.  
These changes ensure it happens on boot.
=> yabai: load scripting addition in yabai-sa daemon

modules/programs/fish.nix
This is an alternative approach to https://github.com/LnL7/nix-darwin/pull/266
Adds the [babelfish](https://github.com/bouk/babelfish) package for translating the environment to fish at build time, eliminating the need for and performance cost of fenv.
I'm not sure if we want to vendor the package, get it added upsteam in nixpkgs, or some other approach. Ideally nixOS users would receive a similar change to their module as well.
Fixes https://github.com/LnL7/nix-darwin/issues/269
=> Native fish environment with babelfish

modules/services/dnsmasq.nix, tests/services-dnsmasq.nix
Older approach seems to not work on macOS 11 Big Sur for some reason.
=> Use separate config option to set port of DNSmasq

modules/programs/fish.nix
Referring to the deprecated package first causes
an error to be thrown before the correct package can be selected.
Fixes issue found in https://github.com/LnL7/nix-darwin/pull/270#issuecomment-769923166
=> fish: fix fenv reference on 20.09

modules/programs/gnupg.nix
The agent is restarted automatically after it has been launched
successfully, this creates a lot of noise in the logs. This change
reloads the agent only if it has crashed, i.e. returns with a non-zero
exit code.
=> Fix gnupg-agent being kept alive

modules/programs/fish.nix
Necessary as of https://github.com/NixOS/nixpkgs/commit/d94921db12d9c9e2d3e9c2e6e25e50f03f789ecb
=> fish: fix fenv function path

modules/nix/default.nix
This ports the `nix.registry` option from NixOS, which allows managing the global flake registry, aka. `/etc/nix/registry.json`.
This allows to define registry items from nix-darwin, and most importantly have it match what the `flake.lock` defines.
---
```nix
{
inputs = {
nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
darwin.url = "github:LnL7/nix-darwin";
darwin.inputs.nixpkgs.follows = "nixpkgs";
};
outputs = { self, nixpkgs, darwin }: {
darwinConfigurations."example" = darwin.lib.darwinSystem {
modules = [{ pkgs, ... }: {
nix = {
package = pkgs.nixFlakes;
registry.nixpkgs.flake = nixpkgs;
extraOptions = ''
experimental-features = nix-command flakes
'';
};
}];
};
};
}
```
`/etc/nix/registry.json` should contain something like this:
```json
{
"flakes": [
{
"exact": true,
"from": { …
```
=> Add nix.registry options

pkgs/darwin-installer/default.nix, pkgs/darwin-uninstaller/default.nix
`stdenv.lib` has been deprecated, and the correct approach is to use `lib` directly through `pkgs.lib`.
=> darwin-[un]installer: Don't reference deprecated stdenv.lib

pkgs/nix-tools/darwin-rebuild.sh
Fixes
```
error: 'info' is not a recognised command'
```
Issue: #307
=> Fix nix flake info error

.github/workflows/test.yml, modules/examples/flake.nix
After #308 is merged, this fixes the github action build. Tested and working on my fork https://github.com/tricktron/nix-darwin/tree/develop.
=> Fixes install flake GitHub action

README.md
I don't have unlimited time to read through the manual installation instructions just to see where the config file goes when I forget. It's not great either that the first line of the README has a path that means nothing at all on macOS. That could be better too but I'm not going to update the project's top tagline in a PR.
=> List the configuration file location in README

modules/homebrew.nix
[x] Tested using `darwin-rebuild switch -I darwin=$(pwd)` using nix daemon
[ ] Update documentation
[ ] write an automated testcase?
...
Reason:
I am currently building a nix package for `brew` which is working in its first alpha version for installing my used "Casks".
(I am happy to share if someone is interested even though I am not sure getting it done the "nix way" 100% - means without non-deterministic side-effects).
I am happy for every comment / feedback :-)
=> homebrew: make brew path configurable

modules/system/defaults/NSGlobalDomain.nix
This adds support for automatic switching between light and dark mode.
=> system.defaults: enable automatic light/dark mode

pkgs/darwin-uninstaller/configuration.nix
`~/Applications/Nix Apps` was added in #31 but the uninstaller was not updated.
=> uninstaller: also remove `~/Applications/Nix Apps`

README.md, default.nix, eval-config.nix, flake.nix, modules/examples/flake.nix
This allows us to specify what kind of darwinSystem we want to build, rather than determining it at evaluation time.
=> Pass system to darwinSystem rather than eval-config.

pkgs/darwin-installer/configuration.nix
apfs.util (or at least it's newer -t flag) has bad exit code semantics
and will return non-zero codes for both success and errors.
Closes #401 and most-likely fixes #378 as well
=> fix dependence on apfs.util exit code

eval-config.nix, modules/documentation/default.nix
Resolves
```
trace: warning: The args argument to evalModules is deprecated. Please set config._module.args instead.
```
`evalModules { args }` and `config._module.args` are equivalent and have been available for years.
Fixes #405
=> eval-config.nix: Fix args warning

modules/nix/nixpkgs.nix
Replace builtins.isFunction with lib.isFunction, which allows functors.
#374 
Not sure this is exactly what is required here, I am not 100% on the nixpkgs functor internals.
=> nixpkgs: Allow functors.

eval-config.nix
This allows more passthrough parameters in compatibility with nixpkgs. (See #392)
=> eval-config: Add check parameter for compatibility with nixpkgs.

pkgs/darwin-installer/configuration.nix, pkgs/darwin-installer/installer.nix
This allows using the installer script independently of `<user-darwin-config>` that isn't working with flakes.
cc @LnL7
=> move installer into a separate file

modules/homebrew.nix
This allows homebrew support to work out of the box on Apple Silicon machines.
See #322 for background discussion.
=> Set brewPrefix defaults according to platform

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/universalaccess.nix, tests/system-defaults-write.nix
See https://github.com/montchr/dotfield/commit/66b90fc02417bc9a719d354f1c6aad0f1bc0eee6 for successful implementation.
- Add an option to disable transparency in system UI (especially noticeable in the menu bar).
- **source:** https://github.com/mathiasbynens/dotfiles/blob/66ba9b3cc0ca1b29f04b8e39f84e5b034fdb24b6/.macos#L28-L29
- **personal note:** I recently updated to Monterey and found that my menu bar appeared to be light even when I had dark mode enabled. Turns out that turning this setting on "fixes" that behavior.
- Add an option to enable screen zoom while holding the ctrl key and scrolling. Also added the related option for controlling whether the zoomed area will follow the cursor.
- **source:** https://github.com/mathiasbynens/dotfiles/blob/66ba9b3cc0ca1b29f04b8e39f84e5b034fdb24 …
=> defaults: add options for common defaults in the `com.apple.universalaccess` domain

modules/homebrew.nix
Turns out that #418, has a small bug:`pkgs.stdenv.hostPlatform.darwinArch` returns `"arm64"` on `aarch64-darwin` systems not `"aarch64"`.
Instead of changing to code to check whether the value is `"arm64"`, I've changed the predicate to use `pkgs.stdenv.hostPlatform.isAarch64`.
I've tested on my own system and this works properly for both Intel and Apple Silicon Macs now.
=> Fix homebrew.brewPrefix default value on Apple Silicon

pkgs/nix-tools/darwin-rebuild.sh
A similar change was made in nixpkgs which prevented content addressing being used.
https://github.com/NixOS/nix/issues/4784#issuecomment-841824085
https://github.com/NixOS/nixpkgs/pull/123246
=> Don't reset experimental features

eval-config.nix, flake.nix, modules/nix/nixpkgs.nix
This is useful for flake users as they will usually already have an
instantiated Nixpkgs e.g.
let
pkgs = import nixpkgs {
config.allowUnfree = true;
overlays = [ ... ];
}
in darwin.lib.darwinSystem {
inherit pkgs;
}
This change makes `nix-darwin` match the behaviour of NixOS and
`home-manager`.
=> eval-config: Support passing in `pkgs`

modules/services/cachix-agent.nix
Fixes a scary red deprecation notice.
=> cachix-agent: literalExample -> literalExpression

modules/system/defaults/finder.nix
These additional `defaults write com.apple.finder *` options were part of my osx-setup script that I'm porting to nix. These options:
- control whether Finder shows hidden files like `~/.zhsrc`
- control whether to show a bottom status bar (https://snipboard.io/S1agOv.jpg)
- control whether to show UI for path breadcrumbs (https://snipboard.io/Hs2W3M.jpg)
- control the default search scope when searching inside finder
- control the default view style (icons, list, columns, ...)
=> Add additional options to configure Finder

.github/workflows/update-manual.yml, .gitignore
The current `nix-darwin` manual available online hasn't been updated in about 2 years.
This PR adds a GitHub workflow that will automatically update the manual whenever changes to `.nix` files hit `master`.
I tested this on my fork of `nix-darwin`, and it seems to be working properly:
https://malob.github.io/nix-darwin/manual/index.html
For example, you'll notice that the options for the `homebrew` module are now included.
(Closes #436)
=> Add workflow to auto-update manual

modules/system/defaults/NSGlobalDomain.nix, tests/system-defaults-write.nix
This global option shows hidden files everywhere (including open/save/print dialogs). The option introduced in #445 only shows it in the Main finder window.
=> add option to show hidden files everywhere

modules/system/defaults/NSGlobalDomain.nix, tests/system-defaults-write.nix
When true (false), animations like what you observe when opening a new Firefox window with Cmd-Shift-P are shown (not shown).
=> Add NSGlobalDomain.NSAutomaticWindowAnimationsEnabled setting

modules/system/defaults/finder.nix
The default value seems to have been set by mistake. The default value should probably be `null` for anything under `system.defaults`, and the current value contradicts the option description.
=> fix: incorrect default for FXPreferredViewStyle

modules/fonts/default.nix
since 21.05 beta:
https://github.com/NixOS/nixpkgs/blob/e22337c8707f42e21938dc729643fa8904d33aeb/nixos/modules/config/fonts/fontdir.nix#L64
https://github.com/NixOS/nixpkgs/commit/c99bd9bedf7291390c28eddb31f8ed2aeec8ea7f
=> fonts: rename `fonts.enableFontDir` to `fonts.fontDir.enable` in line with NixOS

modules/fonts/default.nix
see https://github.com/LnL7/nix-darwin/pull/456#issuecomment-1105472886
props to @jared-w for spotting my mistake
=> fonts: replace remaining reference to `enableFontDir`

modules/launchd/launchd.nix
This is required if you want to register an "xpc event stream handler". Check out the README for https://github.com/snosrap/xpc_set_event_stream_handler for more info.
I also did this in https://github.com/LnL7/nix-darwin/pull/210 before giving up and making it a local module. This is the only part that has to be upstreamed and I don't want to keep rebasing 😛 so if it's OK, please let me add this!
=> feat: add serviceConfig.LaunchEvents configuration option

modules/system/checks.nix
Closes #451? Waiting to hear back from the OP there, but I think this should resolve it; it did for me.
This PR adds comments to the two `apfs.util` commands to explain on which versions of MacOS each should be used. This should clear up some confusion. Also, I switched the command for adding the necessary line to synthetic.conf to use printf instead because on any shell other than zsh, echo is not a builtin, and `echo '...\t...'` doesn't expand the `\t`, so we end up with a literal `\t` in synthetic.conf.
=> Fix synthetic.conf instructions

modules/misc/lib.nix, modules/module-list.nix
I'm working on https://github.com/divnix/digga/pull/438. The project expects a top level `lib` option in system configuration, which is declared in NixOS, but not in nix-darwin.
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/lib.nix
Description from the option declaration:
> This option allows modules to define helper functions, constants, etc.
=> Add top-level `lib` option based on NixOS

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/ActivityMonitor.nix, tests/system-defaults-write.nix
This PR enables nix-darwin to configure some activity monitor functionality. These options were part of my osx-setup script that I'm porting to nix and mostly taken from https://github.com/joeyhoer/starter/blob/master/apps/activity-monitor.sh.  
Specifically these options enable:
- Configuring which processes to show in the main CPU view
- Configuring the dock icon.
- Configuring the sort column and order of the main window.
=> add options for configuring activity monitor

modules/services/redis/default.nix
Can fix #430 by setting
```
services.redis.enable = true;
services.redis.dataDir = null;
```
I don't need locally my redis persistent 😅
=> modules: make dataDir nullable in redis

.github/workflows/build.yml, .github/workflows/debug.yml, .github/workflows/test.yml, .github/workflows/update-manual.yml
It might be beneficial to set up a matrix ([docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-multi-dimension-matrix)) and run all major supported macOS versions in parallel.
Reason: macos-10.15 is [being deprecated](https://github.com/actions/runner-images/issues/5583) and will be fully unsupported by Aug 30 2022.
=> [github] Use macos-12

modules/nix/nix-darwin.nix
Fix #387. Add nixpkgs `git` to `PATH` before `/usr/bin/git` so that when `nix flake metadata` invokes git, it does not invoke the one that complains with xcode-select.
When I run `set -x; source ./result/sw/bin/darwin-rebuild switch --flake '.#myhost'`, I see that darwin-rebuild sets `PATH=/nix/store/nnn-nix:…:/usr/bin:/nix/store/nnn-git/bin:….` before running `nix --extra-experimental-features 'nix-command flakes' flake metadata --json -- .` This results in the error
```
error: getting the HEAD of the Git tree '/Users/yonran/Documents/nixdesktop' failed with exit code 1:
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
```
This commit puts git in `extraPath`, …
=> Fix nix-rebuild --flake without XCode command line tools

modules/system/defaults/dock.nix, tests/system-defaults-write.nix
add an option to make the appswitcher being displayed on all available monitors
=> feat: provide option to display the appswitcher on all displays

modules/environment/default.nix, modules/programs/fish.nix, tests/programs-zsh.nix
Aliases should be escaped.
I only ran into problem with aliases. Is there anything else that should be escaped?🤔
=> add escape to shell aliases

modules/module-list.nix, modules/services/gitlab-runner.nix
This can be used similar to the linux service (in fact the module is almost identical to the linux one) with
```nix
users.knownGroups = [ "gitlab-runner" ];
users.knownUsers = [ "gitlab-runner" ];
services.gitlab-runner = {
enable = true;
extraPackages = [ pkgs.nix ];
services = {
"aarch64-darwin-1" = {
registrationConfigFile = pkgs.writeText "gitlab-runner-registration" ''
CI_SERVER_URL=<gitlab server>
REGISTRATION_TOKEN=<token from gitlab>
'';
executor = "shell";
tagList = [ "aarch64-darwin" "nix" ];
};
};
};
```
now, whether or not using a shell executor is a smart idea is a question one needs to be aware of when doing this.
One thing to note: it requires
```nix
networking.hostName = ...
```
to be set, *but* this fails with
```
configuring networking...
SCPreferencesSetLocalHostName() …
```
=> adds gitlab-runner

modules/services/gitlab-runner.nix
* replace all occurrence's with literalExpression
* fixes #504
=> fix(gitlab-runner): deprecated literalExample

modules/examples/simple.nix
One of the comments in the simple example config looks like it's trying to explain `programs.zsh.enable = true` on the following line, but is referring to `/etc/bashrc`. I assume it should be referring to `/etc/zshrc` instead. Hope this helps!
=> Fix copypasta in simple example

pkgs/nix-tools/darwin-rebuild.sh
After NixOS/nix#6676, the following warning is displayed when running `darwin-rebuild switch`:
> warning: $HOME ('/Users/jamie') is not owned by you, falling back to the one defined in the 'passwd' file.
This happens because, on macOS `sudo` does not set `$HOME` by default, the `-H` flag needs to be added for it to do so.
Fixes: #481
Fixes: #477
=> Add `-H` to `sudo nix-env [...]` calls in `darwin-rebuild.sh` to deal with warning

modules/nix/default.nix, modules/system/defaults-write.nix, modules/system/defaults/NSGlobalDomain.nix, modules/system/defaults/dock.nix, tests/system-defaults-write.nix
This PR transitions all options that use strings to represent float values to use builtin floats. 
This change is not backwards compatible, since using string values for those options will produce and error, but to ease the transition, I've create a `floatWithDeprecationError` type, that will print a helpful error message informing users of the change.
Fixes: #454
=> Transition to using native floats for option types

modules/services/yabai/default.nix
[7 May 2020](https://github.com/LnL7/nix-darwin/pull/196#discussion_r421693792):
> This was only added recently to nixpkgs, this default shouldn't be included until 20.09 has been released for a while so people using the stable channel don't run into issues.
So, we can add default value now.
=> yabai: set default package

tests/fonts.nix
Locally running the tests currently gives a warning, because the fonts api has changed.
Updated it to align with the current fonts module.
=> fix: adapt fonts tests to use newer module api

modules/services/tailscale.nix
- [tailscale: fix tailscaled not running as root](https://github.com/LnL7/nix-darwin/commit/0ae311e1c74ad88a74b3ee5d897d4df4f633044f)
Run `tailscaled` using a system daemon as it does not work as a non-root
user without `userspace-networking`.
Also, remove the broken warning relating to setting the search domain.
Manually adding the search domain to `networking.search` isn't necessary
to use only machine names to refer to other machines.
- [tailscale: prevent significant DNS footgun](https://github.com/LnL7/nix-darwin/commit/bdd5d81b13cd5886eab49d23472233b9b6e7f606)
=> Fix Tailscale module

eval-config.nix
This enables using flake `lib.darwinSystem` function with a custom lib, much like how `nixosSystem` allows the same.
=> feat(eval-config): make lib overridable

doc/manual/options-to-docbook.xsl
See https://github.com/NixOS/nixpkgs/issues/196651 for context.
__NOTE__: untested because I haven't found a quick way to build the manual without building a nix-darwin configuration, so it would be cool if someone could do a sanity-check before merging!
=> Fix manual by escaping `&quot;` as well

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/CustomPreferences.nix, tests/system-defaults-write.nix
Fixes #517
Allows to specify arbitrary options to configure so custom software using `defaults` and system options not yet supported in `nix-darwin` can be configured 
```
system.defaults = {
CustomUserPreferences = {
"NSGlobalDomain" = { "TISRomanSwitchState" = 1; };
"com.apple.Safari" = {
"com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" =
true;
};
};
}
```
=> Custom defaults writes

modules/fonts/default.nix
At least this allows to configure Ventura with nix-darwin, doesn't change behaviour on older versions.
=> fixes #559, #485: workaround for broken fontrestore on Ventura

modules/system/applications.nix
This PR supercedes #226.
So far application bundles were always linked to `~/Applications` or
`~/Applications/Nix Apps` if the former was an existing directory.
In nix-community/home-manager#1341 a conflict was found with suggested
new Home Manager behavior, where applications installed through Home
Manager would end up in `~/Applications/Home Manager Apps`. This was in
an attempt to make them discoverable through Spotlight but further
investigation suggest Spotlight does not pick up symlinked apps (details
in the issue).
However, there are other programs that expect to be able to write to
`~/Applications` so taking over the directory is unfortunate.
PR #226 dropped linking `~/Applications` and instead made sure the
directory exists so we can always link in `~/Applications/Nix Apps`. …
=> Disable taking control of ~/Applications folder MkII

README.md
Spell NixOS with capital OS like it's on the official website, etc. This is just a really small change, but it just bugs me :p
=> Correct capitalisation of NixOS

pkgs/nix-tools/darwin-rebuild.sh
```
❯ darwin-rebuild switch --flake . --dry-run             
error: unrecognised flag '--dry-run'
Try 'nix --help' for more information.
```
It is caused by `nix --extra-experimental-features 'nix-command flakes' flake metadata --json --dry-run -- .`, which is invalid because `nix flake metadata` doesn't accept `--dry-run` flag.
This PR fixes this by excluding build-only flags from `nix flake metadata` invocation.
=> Fix darwin rebuild fails with flake and dry-run

modules/services/postgresql/default.nix
I want a newish postgres config to work on my Mac.
This contains a little hack (putting the check-config derivation into
the start script as a comment) to deal with not having #356. Also,
it does not implement the stuff that requires a postStart script.
It's otherwise identical to the upstream module.
I changed the service to use utf8 always because the charset option got deleted in the upstream module. It seems to work and I can connect to it.
=> services/postgresql: update to the latest upstream nixos module

modules/system/defaults/NSGlobalDomain.nix, tests/system-defaults-write.nix
Normally, the system region setting determines whether the clock uses 12- or 24-hour time. This flag allows users to override this setting and use 24-hour time even if their region does not.
=> Add option to use 24-hour system time

modules/system/defaults/GlobalPreferences.nix
Adds support for the `com.apple.mouse.scaling` GlobalPreferences setting. This is [useful for disabling mouse acceleration](https://devhints.io/macos-mouse-acceleration).
=> add mouse scaling system setting

README.md
Removes the inaccurate notice in the README that says the uninstaller will uninstall Nix alongside nix-darwin.
=> Remove inaccurate notice that the uninstaller uninstalls Nix

README.md, modules/meta.nix, modules/module-list.nix, modules/services/hercules-ci-agent/common.nix, modules/services/hercules-ci-agent/default.nix, modules/services/hercules-ci-agent/settings.nix
Adds hercules-ci-agent.
Installation instructions are provided on hercules-ci.com / docs.hercules-ci.com and will be updated after merge.
A typical configuration consists of `services.hercules-ci-agent.enable = true` and two or three files in `/var/lib/hercules-ci-agent`.
For users migrating from old services and/or the current flake darwinModule (which will be updated to match this PR):
-  The `nix-darwin` module uses new user id and group id numbers, to match the upstream `nix-darwin` module.
The main benefit of the upstream change is that the agent user will not appear as a normal (human) user on the system.
To migrate, run:
```shell
sudo dscl . -delete '/Groups/_hercules-ci-agent'
sudo dscl . -delete '/Users/_hercules-ci-agent'
sudo darwin-rebuild switch
sudo chown -R …
```
=> Add `services.hercules-ci-agent`

modules/services/wg-quick.nix
This PR fixes a typo in the `modules/services/wg-quick.nix` implementation
`concatStringsep` -> `concatStringsSep`
=> fix(wg-quick): builtins function typo

modules/fonts/default.nix
Without this, attempts to build the fonts dir with repeated font
packages in `fonts.fonts` will yield:
```
ln: failed to create symbolic link '/nix/store/6im9rm87nxc82nqbv350hfp2w7ja1z47-fonts/Library/Fonts/IBMPlexSansThai-Thin.otf': File exists
```
=> fix(modules/fonts): ignore repeated fonts

.github/workflows/test.yml, pkgs/nix-tools/darwin-rebuild.sh
Fixes #597. Tested on my mac.
Problem - from that same RFC that is quoted:
```
For example, matching the above expression to
http://www.ics.uci.edu/pub/ietf/uri/#Related
results in the following subexpression matches:
$1 = http:
$2 = http
$3 = //www.ics.uci.edu
$4 = www.ics.uci.edu
$5 = /pub/ietf/uri/
$6 = <undefined>
$7 = <undefined>
$8 = #Related
$9 = Related
```
and when building the URI, we concatenated:
```
flake=${group 2}${group 4}${group 5}${group 6}
```
Which results (for the URL example in question) in:
```
flake=httpwww.ics.uci.edu/pub/ietf/url/
```
Thus, this MR adds the missing `://`. 
I could've also just used group 1 instead of 2 and group 3 instead of 4, but I think the current way is more clear and readable and there are no problems with naming (how to name `scheme` with …
=> fix: add '://' to built flake uri

modules/system/patches.nix
Currently, `system.patches` doesn't work because it will attempt to first detect if the patch has already been applied by checking if it can be applied in reverse.
However, when that happens, `patch` detects that the supplied patch is incorrectly reversed and attempts to ask the user if they want to "Ignore -R":
```
Unreversed (or previously applied) patch detected!  Ignore -R? [y]
```
Because the output is piped to `/dev/null` the user will basically see nothing and `darwin-rebuild switch` will hang until the user presses "Enter" (possibly to check if the terminal is frozen). At which point, patch will ignore the --reverse and exit successfully, preventing the patch from being applied at all.
This change fixes that bug by using `--force` when running the `patch` command with `--reverse`. …
=> Fix system.patches

modules/nix/default.nix
This was
mkDefault { } // filterAttrs () x
which is interpreted as
(mkDefault { }) // (filterAttrs () x)
but the intention is
mkDefault ({ } // filterAttrs () x)
Resulting in lastModified, rev, etc. not being included. This is essentially just bringing this clause up-to-date with the one from NixOS.
=> nix: Fix registry extra attrs not being applied

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/screensaver.nix, tests/system-defaults-write.nix
Add support of two new macOS parameters.
- com.apple.screensaver.askForPassword
- com.apple.screensaver.askForPasswordDelay
https://developer.apple.com/documentation/devicemanagement/screensaver
=> feat(screensaver): add support of askForPassword and askForPasswordDelay

modules/lib/write-text.nix, modules/programs/ssh/default.nix, modules/system/etc.nix, tests/programs-ssh.nix
Resolves #152 
Example configuration:
```nix
{ config, pkgs, ... }:
{
users.users.foo.openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA..." ];
}
```
=> Manage SSH authorized keys for users

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/clock.nix, tests/system-defaults-write.nix
Expose menubar clock preferences through nix-darwin.
Works locally (apple silicon, Mac 13.3.1).
1. Does anyone know what the difference is between
```
defaults write com.apple.menuextra.clock ShowDate -int 1
```
and
```
defaults write com.apple.menuextra.clock ShowDate -int 2
```
?
2. Is this the expected way to organise the nix-darwin namespace (`system.defaults.clock.xyz`) vs the actual namespace (`com.apple.menuextra.clock.xyz`)?
Edit: Technically, from the name "clock" it's not clear that this is about the clock in the menubar. That's an argument against the hierarchy I chose.
=> feat: defaults write com.apple.menuextra.clock

modules/services/buildkite-agents.nix
This might be useful when some non-nix packages need to be provided, e.g. 'brew'.
=> buildkite-agent: allow 'types.path' in runtimePackages

pkgs/darwin-installer/installer.nix
=> darwin-installer: fix `/run` not getting created

.github/workflows/build.yml, .github/workflows/debug.yml, .github/workflows/update-manual.yml
Not all workflows were updated but some were, this fixes the inconsistency.
=> GHActions: Bump install-nix-action to v22

README.md
I was pretty confused on how to use `inputs`, and thanks to the [help of some people on #macos:nixos.org](https://matrix.to/#/!lheuhImcToQZYTQTuI:nixos.org/$tYXRDztoqBWcLVHmSSaFuAO4NTVhHz_EZmSsJ5FvLUI?via=nixos.org&via=matrix.org&via=nixos.dev) I was able to get my configuration working using `specialArgs`.
This PR updates the readme to better document how to use `inputs` when using nix-darwin with flakes. It also documents how `specialArgs` could be used to also access things from `configuration.nix`.
=> docs: clarify how to use inputs with flakes

modules/nix/default.nix
This add the `protocol` option to the Nix build machines config.
[Simple copy and paste of the NixOS config option](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/services/misc/nix-daemon.nix#L231).
=> nix: Add build machines protocol option.

modules/fonts/default.nix
This just adds the description —  #624 allows font packages with conflicting font file names to coexist, and through the use of `ln -f` selects the latter.
(I've had a patch to apply the `ln -sf` change for a while, but I didn't realize others were hitting this issue, too — I'll work on pushing my improvements up stream.)
=> Document font overriding behaviour

eval-config.nix
Fixes #701. Note that this is *not* a viable long-term solution; currently, all `mdDoc`-tagged documentation is omitted from the manual build entirely(!). We need to move over to the new NixOS Markdown-based documentation generator ASAP; the DocBook output won't live for much longer. I'm working on this and it looks like it won't be too difficult (thanks @pennae for pointing me to [nix-doc-munge](https://github.com/pennae/nix-doc-munge)!), but the changes will be more extensive and it's not going to be possible to maintain simultaneous compatibility with older nixpkgs (at least for the manual build). I'm sending this just to unbreak people's systems while I work on a longer-term solution.
=> eval-config.nix: readd `lib.mdDoc` temporarily

modules/system/defaults/ActivityMonitor.nix
treewide these seem to be the only settings that aren't unset by default which seems inconsistent
there wasn't any discussion about this on the original PR https://github.com/LnL7/nix-darwin/pull/447
=> activity monitor: change settings to null

modules/services/buildkite-agents.nix
Add missing 'NIX_SSL_CERT_FILE'
=> buildkite-agent: fix launchd daemon environment

default.nix, modules/documentation/default.nix
This fixes
error: The option `system.nixpkgsRevision' is used but not defined.
While also giving non-flakes users the possibility to pick up a `.rev` from their nixpkgs source automatically if it exists.
`system.nixpkgsRevision` did not get an option default because how bad the missing data is depends on the use case. This might be a little paranoid, admittedly.
=> Fix doc revision eval error

pkgs/nix-tools/darwin-rebuild.sh
This flag allows forcing remote flakes (e.g. `github:foobar/nix-config`)
to be force-refreshed, which is required for quickly
iterating/activating a remote config.
=> feat(darwin-rebuild): support --refresh

doc/known-files/2c28f4fe3b4a958cd86b120e7eb799eee6976daa35b228c885f0630c55ef626c, modules/nix/default.nix, modules/services/tailscale.nix
- Removed `services.tailscale.domain` as Tailscale automatically sets the search domains by creating `/etc/resolver/search.tailscale`
- Fixed MagicDNS when `Override local DNS` is enabled and `100.100.100.100` is not set as a DNS server by creating `/etc/resolver/ts.net` (https://github.com/tailscale/tailscale/issues/8436)
- Removed `services.tailscale.magicDNS` as MagicDNS now works with or without adding `100.100.100.100` as a DNS server
- Added option for implementing `Override local DNS` by setting `100.100.100.100` as the sole DNS server locally until it is implemented in tailscaled (https://github.com/tailscale/tailscale/issues/1338)
cc @sellout
=> tailscale: improve MagicDNS setup

modules/module-list.nix, modules/nix/default.nix, modules/nix/linux-builder.nix
This PR adds `darwin.builder` as a `launchd` service :tada: 
Depends on https://github.com/NixOS/nixpkgs/pull/236389 as it expects `darwin.builder` to run on port 31022 by default
=> nix/linux-builder: init

modules/nix/linux-builder.nix
- `modules` cannot be a nested list
- `nix.settings.extra-trusted-users` might not be set
=> linux-builder: fix evaluation errors

modules/programs/zsh/default.nix
caught the issue described in here https://github.com/NixOS/nixpkgs/issues/30121 and feeling it is worth to patch a fix here. 
basically the issues is that when you run a command with output missing the new line ending, it will not be displayed.
```
root@nixos> echo -n "abc\ndef"
abc
```
something like this ☝️
=> fix zsh eating output without new line ending

README.md, modules/examples/flake/flake.nix
After #723, `nix-darwin` no longer uses the name of the flake input (previously using `darwin`), which means users can use any name they like. One benefit for users using `nix-darwin` instead of `darwin` as the name of their flake input is if they generate `nix.registry` entries from `inputs` (like [`nix.generateRegistryFromInputs`](https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/master/lib/options.nix) from `flake-utils-plus.darwinModules.autoGenFromInputs`), then their registry will have `nix-darwin` pointing to the version used in their configs, rather having both `darwin` and `nix-darwin` in the registry.
Closes https://github.com/NixOS/flake-registry/pull/47
=> flake: use `nix-darwin` instead of `darwin`

.github/workflows/test.yml
turns out it's not just a docs change :thinking:
=> workflows: use `nix-darwin` instead of `darwin`

modules/services/yabai/default.nix
This closes #729 by changing the type of the `services.yabai.extraConfig` option from `str` to `lines`. This allows defining `extraConfig` in multiple places in your config, with the final value being all definitions concatenated with `\n`.
=> use `types.lines` for yabai.extraConfig option

modules/services/activate-system/default.nix, modules/system/activation-scripts.nix, modules/system/etc.nix
This ensures that activation fails early if there are any `/etc` files with unexpected state, rather than leaving the system half-activated.
Here be dragons, obviously; it would be quite bad to get anything wrong. I tried to write this as clearly as possible and I think it's a lot easier to follow than the previous version, but it should still be carefully reviewed. It worked for all the cases I tested. I endeavoured to follow the logic of the previous version as closely as possible, except for two cases, which should both be more conservative than the previous version:
* We don't treat an `/etc` file containing the string `/etc/static` as carte blanche to overwrite it. (Why would we...? This one really confuses me. @LnL7 do you remember what's going on there?)
* We delete links into …
=> etc: check for existing files during checks stage

modules/module-list.nix, modules/services/eternal-terminal.nix, release.nix, tests/services-eternal-terminal.nix
Adds an eternal-terminal module. Much of the implementation is borrowed from the corresponding nixos module:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/eternal-terminal.nix
=> eternal-terminal: add module

eval-config.nix, modules/documentation/default.nix
See [the Nixpkgs manual]. This allows modules to declare themselves as being only for NixOS or nix-darwin, reducing compatibility risks. Unmarked modules will continue to behave as before. Technically a breaking change, but any configuration importing a module explicitly marked as NixOS-specific was probably broken already.
[the Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/#module-system-lib-evalModules-param-class
=> eval-config: set `class`

eval-config.nix, modules/documentation/default.nix
Reverts LnL7/nix-darwin#744
22.11 doesn't have this, sigh; should have double-checked. cc @Enzime
=> Revert "eval-config: set `class`"

modules/programs/fish.nix
This option should probably be dropped but I'd prefer to batch that with using Babelfish by default (or unconditionally, as Home Manager does) so as to avoid multiple independent breaking changes.
Fixes: #632
=> fish: add default for `babelfishPackage`

modules/system/defaults/finder.nix
`string` was changed from deprecation warning to error in https://github.com/NixOS/nixpkgs/commit/c59c6b1c57da542b6b4af5d2ac27d1b99e7f0c5e
=> finder: `types.string` -> `types.str`

modules/fonts/default.nix
There aren't actually any dfont-formatted fonts in nixpkgs, but I'm using one in my personal config. This used to work, prior to bc776e4940106a2578998dd3117a76d62ec0a8c, but the font file is now ignored.
Supporting a format that isn't supported by nixpkgs feels a bit weird, but I think it's okay because nixpkgs includes a lot of formats that are not supported on darwin.
=> Add support for dfont to the fonts module

modules/time/default.nix
Fixes #359
As noted in #359, the timezone is still set correctly despite the error message. So, the message appears to be irrelevant. No one in that thread has reported observing other side effects that may relate.
=> time: bury confusing `systemsetup -settimezone` output

README.md, pkgs/nix-tools/darwin-rebuild.sh
When running `darwin-rebuild switch --flake flake-uri` on other networks (like eduroam), I'm getting issues  since my hostname isn't actually what I expect in my flake config. By using the LocalHostName it won't change suddenly when being on other Wi-Fi:s.
Maybe there's a setting for this I've missed but otherwise I think this could be a reasonable change, if you agree.
=> Use LocalHostName in darwin-rebuild with a flake

modules/programs/ssh/default.nix, release.nix, tests/programs-ssh-empty-known-hosts.nix
I noticed that I'm getting an empty `/etc/ssh/ssh_known_hosts`, and it seems that we were not gating its config.
=> programs.ssh: write ssh known_hosts only if there are any set

pkgs/nix-tools/darwin-rebuild.sh
> https://github.com/LnL7/nix-darwin/pull/509#issuecomment-1232514860
> It might be nice to add `-H` to the `sudo "$systemConfig/activate"` line as well. A quick skim of the activate script doesn't show any references to `$HOME` but it's still probably a good idea for consistency, especially as someone could write a custom activation script that references this variable or invokes a command that itself consults this variable, and system activation should probably try to avoid any dependency on the initiating user.
Running `nix store diff-closure` in a activation script displays:
```
warning: $HOME ... is not owned by you, falling back to the one defined in the 'passwd' file.
```
=> darwin-rebuild: add `-H` to sudo for `$systemConfig/activate`

modules/nix/linux-builder.nix
Hello!
My mac m2 is configured with this project using this configuration:
```nix
nix.linux-builder.enable = true;
```
this linux builder is super easy to setup and has been tremendously useful, however I am unable to run nixos tests configured like this:
```nix
{
inputs = {
nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
};
outputs = {
self,
nixpkgs-unstable,
...
}: {
checks.aarch64-darwin = let
pkgs = nixpkgs-unstable.legacyPackages.aarch64-linux;
in {
simple = pkgs.nixosTest {
name = "simple-test";
nodes.default = {};
testScript = ''
start_all()
default.wait_for_unit("multi-user.target")
'';
};
};
};
}
```
due to this error:
```sh
$> nix flake check
error: a 'aarch64-linux' with features {kvm, nixos-test} is required to build …
```
=> Provide 'supportedFeatures' option to the linux builder module

modules/nix/linux-builder.nix
macOS has a daily task that cleans files in `/tmp` that haven't been accessed for 3+ days. This task can clean up the folder used for sharing certs with the linux-builder VM, which would cause the VM to lose the ability to connect to https URLs (such as the nixpkgs binary cache). Using a subfolder of `/run` avoids this issue.
Fixes #768
=> linux-builder: avoid /tmp for certs

modules/nix/linux-builder.nix
Using the type `deferredModule` fixes `pkgs` not being accessible as a module argument (apart from `config._module.args.pkgs`).
Changing the interface from a list to a module means that options can be easily set with fully quantified path syntax like
```
nix.linux-builder.config.virtualisation.darwin-builder.hostPort = 22;
```
=> linux-builder: change from `modules` to `config`

pkgs/nix-tools/darwin-rebuild.sh
restore sudo environment PATH when Cyberark EPM is setting secure_path in sudo config. Fixes LnL7/nix-darwin/issues/798
=> fix(#798): darwin-rebuild support for Cyberark EPM

modules/security/pki/default.nix, modules/services/nix-daemon.nix
Made is possible to disable the management of /etc/ssl/certs/ca-certificates.crt by nix-darwin.
Use case: we distribute corporate CA certificates through our MDM. Keeping them in sync with our shared nix config is a hassle. Instead, we plan on adding a nix-darwin module that sets up a daemon that will periodically export the bundle of certificates from macOS keychain into /etc/ssl/certs/ca-certificates.crt. To make this possible, we need to put /etc/ssl/certs/ca-certificates.crt out of the control of nix-darwin.
=> Add security.pki.installCACerts config

modules/system/etc.nix
I have another activationScript which traps errors. Currently `etcProblems` can be unbound.
=> Fix unbound variable `etcProblems`

README.md
Added a link to the "Flakes (experimental)" section in the README, for the "note darwin-installer is no longer needed" section, as per issue 803.
=> Add flakes section reference in Installation section

.github/workflows/test.yml
Use Nix 2.13.6 which is the default version for NixOS 23.05.
=> fix: tests failing to build on unstable Nix

default.nix, flake.nix, modules/nix/nix-darwin.nix, pkgs/darwin-uninstaller/configuration.nix, pkgs/darwin-uninstaller/default.nix
I ran `nix flake check` and that worked, and I ran `nix-build . -A uninstaller`, and that worked, but I haven't tested it beyond that yet.
Closes #804
=> Install darwin-uninstall by default, which includes the 'empty' config it switches to

pkgs/nix-tools/darwin-rebuild.sh
darwin-rebuild: fix sudo invocation on High Sierra
The version of sudo on macOS 10.13 High Sierra does not support the
`--preserve-env=LIST` option syntax, which is used here to preserve
PATH.
Override sudo with a shell function that checks for the availability of
this option syntax, and do not pass PATH otherwise.
Also move the prefix env command in the sudo invocations into the new
sudo function.
=> darwin-rebuild: fix sudo invocation on High Sierra

modules/system/defaults/GlobalPreferences.nix
Follow up to https://github.com/LnL7/nix-darwin/pull/838 . 
The change requires a float number but example is integer and will not build.
=> GlobalPreferences: fix mouse scaling example

modules/launchd/launchd.nix
Not sure if this is intended but looks like `serviceConfig.StartCalendarInterval` has to wrapped in a list so would be good if the example follows that assumption as well.
```
error: A definition for option `launchd.user.agents.[...].serviceConfig.StartCalendarInterval' is not of type `null or (list of (submodule))'. Definition values:
- In `<unknown-file>':
{
Hour = 0;
Minute = 0;
}
```
=> Fix type error

modules/users/default.nix, tests/users-groups.nix
Properly detect the binary name (not just /nix/store/...-bash, but include the .../bin/bash), and use the symlinked name which also appears in /etc/shells.
=> fix: user shell path handling

modules/networking/default.nix, tests/networking-shell-escape.nix
Fix a bug where using a single quote in any of the networking names caused the following error:
```
/nix/store/8zbx7q8xxrsd46m0n0bspnjvm27ak3sr-darwin-system-24.05.20240108.317484b+darwin4.0dd382b/activate: line 264: unexpected EOF while looking for matching `''
```
Example config:
```nix
networking.hostName = "Adams-MacBook-Pro";
networking.computerName = "Adam's MacBook Pro";
```
=> fix shell escaping in networking config

modules/programs/zsh/default.nix
=> Add option to disable zsh global compinit

modules/launchd/launchd.nix
Per: https://developer.apple.com/library/archive/technotes/tn2083/_index.html#:~:text=If%20you%20want%20to%20run%20in%20more%20than%20one%20session%20type%2C%20you%20can%20set%20LimitLoadToSessionType%20to%20an%20array%2C%20where%20each%20element%20is%20a%20session%20type%20string.
LimitLoadToSessionType can also be an array if more than one session type is desired.
=> Allow launchd serivceConfig.LimitLoadToSessionType to be a list

modules/examples/lnl.nix, pkgs/nix-tools/darwin-rebuild.zsh-completions, pkgs/nix-tools/default.nix
Added a few more options that weren't in the example. Not checked to see if all arguments/flags have completions.
=> Add zsh completions to darwin-rebuld by default

modules/services/yabai/default.nix
The --check-sa and --install-sa flags were removed in favor of --load-sa as of version 5.0.0 of Yabai.
https://github.com/koekeishiya/yabai/blob/ee0137f37ded4309cb40b7f38817b5abd90fb592/CHANGELOG.md?plain=1#L83
=> services/yabai: Remove --check-sa and --install-sa flags

modules/services/yabai/default.nix
`enableScriptingAddition` no longer triggers IFD by using runCommand to generate `sudoers.d/yabai`, instead of `builtins.hashFile` and interpolating the string in nix.
=> services/yabai: Remove IFD

modules/module-list.nix, modules/security/sudo.nix
This adds the option `security.sudo.extraConfig`, which puts a file in `/etc/sudoers.d`. Because macOS' `/etc/sudoers` file includes these lines:
```
#includedir /private/etc/sudoers.d
```
this allows extra configuration, while also matching the NixOS option and thus allowing common config across operating systems.
Closes #793
=> security.sudo.extraConfig: init

modules/module-list.nix, modules/services/github-runner/config.nix, modules/services/github-runner/default.nix, modules/services/github-runner/options.nix, release.nix, tests/services-github-runners.nix
Adds a new module which allows to configure multiple GitHub self-hosted runners on Darwin. The module is heavily inspired by the nixpkgs NixOS module. Its implementation differs in some ways:
- There's currently no way to configure the user/group which runs the runner. All configured runners share the same user and group.
- No automatic cleanup.
- No advanced sandboxing apart from user/group isolation
Closes #582
=> github-runners: init module

modules/nix/linux-builder.nix
This wrangles together changes in the following pull requests (no particular order):
1. #816 by @ethnt to add `systems`.
2. #871 by @stv0g to add `mandatoryFeatures` and `speedFactor`.
3. #877 by myself to add `protocol`.
I've done my best to preserve the original commits and keep authors' credit/contributions.  I did take liberty of sorting the added parameters lexicographically.  Additionally I applied the `defaultText` and `literalExpression` feedback from #816 to the other options.
Thanks for taking the time to review!
=> linux-builder additional options

modules/nix/linux-builder.nix
I've set up my local `linux-builder` to emulate `x86_64-linux` as well as `aarch64-linux` (jury's out as to how well that will work), but I still need to be able to set that option in `/etc/nix/machines`. I've added an option for this in `nix.linux-builder`. Potentially in the future it would be a better idea to simply allow `extraBuilderConfig` or something similar, but I stuck with convention in this PR.
=> Add `nix.linux-builder.systems` option to set corresponding `nix.buildMachines.*.systems` option

modules/nix/linux-builder.nix
This commit passes more options to `nix.buildMachines`. Namely the `mandatoryFeatures` and `speedFactor` settings have been missing.
=> linux-builder: Pass through more options to nix.buildMachines

modules/nix/linux-builder.nix
Of note: I have another pull request (#878) which merges together the existing pull requests that add more option handling all around for `linux-builder`.  This is intended as a way to get a gist for these individualized changes.
This commit adds a protocol option for the `linux-builder` and defaults it to `ssh-ng`.  I have observed it needing this with the following:
``` sh
$ nix store ping --store ssh://linux-builder
Store URL: ssh://linux-builder
$ nix store ping --store ssh-ng://linux-builder
Store URL: ssh-ng://linux-builder
Version: 2.18.1
Trusted: 0
```
This seems to make the difference on whether or not Nix picks up `linux-builder` as an available builder.
=> linux-builder: default pass through protocol to nix.buildMachines

modules/security/sudo.nix
Due to where I put the `lib.mkIf`, the file `/etc/sudoers.d/10-nix-darwin-extra-config` was generated with no content by default on every nix-darwin user's system. This PR fixes the default behavior, while not affecting any users who have set an actual value for the option.
=> security.sudo.extraConfig: fix default behavior

modules/module-list.nix, modules/programs/direnv.nix
Add a module that fully sets `direnv` up and by default also sets up `nix-direnv`. This module is almost identical to the one found in NixOS, but I made a couple of small tweaks (where doc strings were inaccurate for MacOS or deprecated options were unneeded since this is the first introduction of the module to nix-darwin).
I tested this against my nix-darwin config.
=> nix-darwin/programs.direnv: init

modules/module-list.nix, modules/system/activation-scripts.nix, modules/system/nvram.nix, modules/system/startup.nix
Adds an option `system.startup.chime`, which can either be `null` (don't change the current setting), `true` (enable the startup chime), or `false` (disable the startup chime).
Because the startup chime settings are stored in NVRAM, I also added an internal `system.nvram.variables` option, rather than implement NVRAM settings specifically for the startup chime.
Will close #885
=> `system.startup.chime`: init

modules/nix/default.nix
This commit updates the nix.conf validation logic to accommodate different versions of Nix. It introduces a conditional assignment of the `showCommand` variable, which determines the appropriate command to use based on the Nix version. For versions at least "2.20pre", it uses "config show"; otherwise, it falls back to "show-config". This change ensures compatibility across various Nix releases.
Same as fix for NixOS - https://github.com/NixOS/nixpkgs/pull/271423
=> Support new nix 2.20 command syntax

modules/system/defaults-write.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/fixtures/system-defaults-write/activate.txt, tests/system-defaults-write.nix
Currently, the `-array` value for `writeValue` produces incorrect arguments for `defaults` like so
```ts
-array -string 'blah' -string 'blah'
```
Complex container values like `-array` and `-dict` have their own DSL which does not allow specifying all data types. Instead of using the DSL use plist fragments instead. 
The man page for `defaults` writes the following, below. This doesn't give much guidance on passing values with containers, but there's a feature to pass plist fragments for much more complex use-cases, mentioned as `<value_rep>` from `defaults --help`:
https://shadowfile.inode.link/blog/2018/06/advanced-defaults1-usage/#container-types
```
...
write domain key 'value'
Writes value as the value for key in domain.  value must be a property list, and must be enclosed in single …
```
=> fix writing values with containers

modules/users/default.nix
Fixes an issue when the group or user doesn't already exist.
```
/nix/store/nbnhpscrj78yfpv0537acjzsi8blkvva-darwin-system-24.05pre-git+darwin4.4b9b83d/activate: line 733: [: : integer expression expected
```
https://github.com/nix-community/infra/actions/runs/7079905777/job/19267084113#step:5:184
=> users: fix `forceRecreate` bash comparison

modules/system/defaults/dock.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
Applications added to the dock point to an old derivation when a new derivation of an application is added to the Nix store. This allows configuring the persistent applications to display system apps or apps in the Nix store.
Updates require re-login or restarting the Dock process e.g. `killall Dock`.
Dependent on: #897
Supersedes the old PR: #619
=> Add support for persistent-apps in dock

modules/module-list.nix, modules/services/trezord.nix
This adds a small module for configuring the trezor-bridge service, trezord. This service enables users to interact with their Trezor hardware wallet through the trezor suite web interface, or to use the device for U2F auth, SSH login, GPG or password mgmt. https://trezor.io/learn/a/what-is-trezor-bridge
The options were copied directly from the nixos service module here: https://github.com/NixOS/nixpkgs/blob/9d6e454b857fb472fa35fc8b098fa5ac307a0d7d/nixos/modules/services/hardware/trezord.nix#L16
The implementation was adapted from the nixos module's systemd service to a launchd user agent.
Tested successfully locally on an Air M2.
=> trezord: Add launchd user agent service module for configuring trezord

modules/meta.nix
Unless will fail on nix eval, e.g.,
```sh
nix eval .#darwinConfigurations.<your-host-name>.options
```
will fail.
=> Use valid maintainer in meta example

.github/workflows/test.yml, .github/workflows/update-manual.yml, README.md
Sounds like a prerequisite for all PRs trying to drop `lib.mdDoc`?
=> ci, readme: update stable nixpkgs to 23.11

modules/services/nix-daemon.nix
1048576 matches the nixos/nix plist
https://github.com/NixOS/nix/blob/e3a4e40a354e1c2d177541d24d6a86a001fa87c7/misc/launchd/org.nixos.nix-daemon.plist.in#L29
=> nix-daemon: increase SoftResourceLimits.NumberOfFiles

modules/services/cachix-agent.nix
One of cachix-agent's dependencies, `hs-certificate`, makes calls to `security`. This lives in `/usr/bin`, which isn't available from launchd. This commit makes the system paths available to cachix-agent.
Fixes #924.
cc @domenkozar
=> cachix-agent: fix crash calling `security`

modules/programs/zsh/default.nix
Zsh prompt Walters causes issues as the default prompt and is a strange default, e.g.
it sets the RPS1.
We should use the same prompt as NixOS uses:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/zsh/zsh.nix#L93
Resolves:
https://github.com/LnL7/nix-darwin/issues/667
Related discussion:
https://github.com/NixOS/nixpkgs/pull/38535
=> Change zsh default prompt

pkgs/nix-tools/darwin-rebuild.sh
Add missing `--offline` and `--substituters` options to `darwin-rebuild` which is impossible to use now.
Closes #608
=> Add offline and substituters flags

modules/system/defaults/dock.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
Added file or directory tile to Dock persistent others.
This will either expand directories or open files directly.
=> Add file or directory tile to Dock persistent others

modules/services/hercules-ci-agent/default.nix
hercules ci agent has the same problem as was reported in https://github.com/LnL7/nix-darwin/issues/924.
I had originally fixed this downstream in nix-community by wrapping `/usr/bin/security` (https://github.com/nix-community/infra/commit/5da85a9b7276f15a64052dcc820ab210d742b914) but here I've reused the same fix that was used for cachix agent.
cc @roberth
=> hercules-ci-agent: fix crash calling `security`

modules/system/defaults/NSGlobalDomain.nix, modules/system/defaults/trackpad.nix
This PR add support for setting the trackpad force click option under NSGlobalDomain, and also to setting the action to take on `com.apple.AppleMultitouchTrackpad` > `TrackpadThreeFingerTapGesture`.
Unintuitively, changing `TrackpadThreeFingerTapGesture` actually changes the `Look up & data detectors` dropdown under Trackpad.
From my tests:
| Look up & data detectors | "com.apple.trackpad.forceClick" | TrackpadThreeFingerTapGesture |
|---|---|---|
| Off | 0 | 0 |
| Force Click with One Finger | 1 | 0 |
| Tap with Three Fingers| 0 | 2 |
=> Add support for trackpad force click

modules/system/defaults/screencapture.nix
This PR adds a new `screencapture.show-thumbnail` option to the `system.defaults` configuration.
This option was found by observing how the output of `defaults read com.apple.screencapture` changed when the 'Show Floating Thumbnail' item was checked and unchecked in the 'Options' menu on the controls bar shown when '⌘ ⇧ 5' (default shortcut) is pressed in MacOS. It determines whether or not a thumbnail will be shown in the bottom right corner of the screen before the screen capture is persisted.
Users may wish to control this option to avoid waiting for the thumbnail to auto-close before accessing the capture.
I tested this by setting my `nix-darwin` input to the source branch as part of a flake including nix-darwin and home-manager, running on MacOS Sonoma 14.5 (23F79), and toggling the …
=> feat: add defaults screencapture show-thumbnail option

modules/launchd/launchd.nix
Add LowPriorityBackgroundIO to the available launchd keys. Useful for backup scripts.
=> launchd: add LowPriorityBackgroundIO config

modules/nix/linux-builder.nix
If you set up a signing key for the `linux-builder` and add that as trusted public key on your machine, you won't need to be a trusted user at all.
=> linux-builder: remove trusted user requirement

README.md, eval-config.nix, flake.lock, modules/documentation/default.nix, modules/nix/nixpkgs.nix
https://github.com/LnL7/nix-darwin/pull/932 already broke these versions, so we can do some clean‐up.
=> Drop compatibility for unsupported Nixpkgs versions

modules/fonts/default.nix, tests/fonts.nix
This uses `/Library/Fonts/Nix Fonts` as suggested by @lilyball, and copies fonts according to their full store path to avoid having to do a slow checksum when you have large fonts (some CJK font packages can be in the hundreds of mebibytes). If adding a few seconds to every activation is considered acceptable, then a simpler flat directory structure could be used instead.
An error is thrown for existing users of `fonts.fonts` that explains the need to manually clean up existing font files.
I'm not completely confident about the dropping of `fonts.fontDir.enable`, but my reading of NixOS's fontconfig code and my old laptop configuration suggest that `fonts.packages` should work even without setting that.
cc @Enzime
=> fonts: reimplement and rename to `fonts.packages`

modules/launchd/launchd.nix, modules/launchd/types.nix, modules/services/nix-gc/default.nix, modules/services/nix-optimise/default.nix
Stricter launchd -> StartCalendarInterval type:
- Verify that the integers passed to `Minute`, `Hour`, etc. are within range.
- When provided, the value for StartCalendarInterval must be a non-empty list of calendar intervals and must not contain duplicates entries (throw an error otherwise).
- For increased flexibility and backwards-compatibility, allow an attrset to be passed as well (which will be type-checked and is functionally equivalent to passing a singleton list). Allowing an attrset or list is precisely in-line with what `launchd.plist(5)` accepts for StartCalendarInterval.
Migrate `nix.gc.interval` and `nix.optimise.interval` over to use this new type, and update their defaults to run weekly instead of daily.
Create `modules/launchd/types.nix` file for easier/modular use of …
=> fix(launchd): improve `StartCalendarInterval`

modules/nix/linux-builder.nix
Before this commit, aarch64 users building the following configuration would end up with an aarch64-linux builder, while after it, they get the x86_64-linux builder they expect:
```nix
nix.linux-builder = {
enable = true;
package = pkgs.darwin.linux-builder-x86_64;
};
```
Before, in order to get an x86_64-linux builder, they would have needed to use this configuration instead:
```nix
nix.linux-builder = {
enable = true;
config.nixpkgs.hostPlatform = "x86_64-linux";
systems = ["x86_64-linux"];
};
```
The reason for this is that the linux-builder module calls `override` on the package option, and the `linux-builder-x86_64` package is also defined using override:
```nix
linux-builder-x86_64 = linux-builder.override {
modules = [ { nixpkgs.hostPlatform = "x86_64-linux"; } ];
};
```
The module …
=> linux-builder: make compatible with cross-arch builder package

modules/system/checks.nix
Follow https://github.com/LnL7/nix-darwin/pull/681, but disable the check automatically if `config.nix.settings.auto-allocate-uids` is explicitly set to `true`.
Note that by default `config.nix.settings = {}`, and this should not affact people who do not configure `nix.settings.auto-allocate-uids`.
=> checks.nix: disable verifyBuildUsers for auto-allocate-uids

modules/services/nextdns/default.nix, tests/services-nextdns.nix
It seems that `escapeShellArgs` doesn't play nicely with launchd, as it surrounds strings with single quotes that are interpreted literally by launchd and passed as arguments (think passing `"'-profile'"` instead of `"-profile"`).
```
Unrecognized parameter: '-profile'
```
```
Unrecognized parameter: '-profile 192.168.4.0/24=XXXXXX'
```
This PR maps the single version of `escapeShellArg` to each argument, and removes the resulting surrounding quotes.
=> Fix NextDNS arguments

CHANGELOG, modules/lib/write-text.nix, modules/programs/ssh/default.nix, modules/system/checks.nix, modules/system/etc.nix, tests/programs-ssh.nix
This is a security fix over a year in the making; I wish I had been able to get it out sooner. Anyone using `AuthorizedKeysCommand` for something else will need to ensure they set it in a later file than `101-authorized-keys.conf`, but hopefully anyone with that customized an SSH setup knows what they’re doing, and I’m not sure how we could better signal that; I doubt anyone reads the changelog but not merged PRs.
This does mean that the Nix store failing to mount could lead to an SSH lock‐out; I’m not sure how we could handle that elegantly and it seems difficult to recover from without direct access anyway (what if your shell is in the Nix store anyway?). It’s possible we could do an ad‐hoc recreation of `copy` here that operates unconditionally on the entire directory, I guess.
=> ssh: use symlinks for `authorizedKeys` options

pkgs/nix-tools/darwin-rebuild.sh
Backported from https://github.com/NixOS/nixpkgs/blob/9995a5d59c59fde96f4ad7d811a8ed832357440f/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L349-L353
Fixes #721
=> Set default flake directory as `/etc/nix-darwin`

modules/module-list.nix, modules/services/jankyborders/default.nix, release.nix, tests/services-jankyborders.nix
[](url)Hi @LnL7,
I hope this message finds you well. I am submitting this PR to add a new NixOS module for [jankyborders](https://search.nixos.org/packages?channel=24.05&show=jankyborders&from=0&size=50&sort=relevance&type=packages&query=jankyborders). This module provides configuration options to enable the service and customize various parameters such as width, active and inactive colors, HiDPI mode, and focus settings.
Official Repo : https://github.com/FelixKratz/JankyBorders
- Added a new module `services.jankyborders` to the NixOS configuration.
- Included configuration options for:
- `width`
- `active_color`
- `inactive_color`
- `hidpi`
- `ax_focus`
- `background_color`
- `blur_radius`
- `blacklist`
- `whitelist`
- Implemented a test case to verify the correct setup of the …
=> module : `jankyborders` for window borders Configuration

modules/services/jankyborders/default.nix
Removing deprecations for Nix 25.05. Apologies for closing the previous PR that got approved - my local nix-darwin fork wasn't in sync and I made a mess.
=> chore: removing deprecations for 25.05 nix

modules/services/github-runner/service.nix
As `/var/run` gets cleared on every reboot, all jobs will fail with `Access to the path '/var/run/github-runners/<name>' is denied.`
=> github-runnners: fix workDir missing on reboot

modules/environment/default.nix, modules/programs/fish.nix
deprecated in https://github.com/NixOS/nixpkgs/commit/473e469d5a921a57b484a09d446cee6c231cd592
=> `mapAttrsFlatten` -> `mapAttrsToList`

modules/system/defaults-write.nix
This can occur if your primary user is not logged in and you try to do a `darwin-rebuild switch`
=> defaults: only restart Dock when user is logged in

modules/services/github-runner/options.nix, modules/services/github-runner/service.nix, modules/system/activation-scripts.nix
Turns out I messed up when testing #1013 and forgot to reboot when testing and the PR didn't actually work.
As `/run` gets recreated every reboot and we can't specify dependencies for launchd, creating the `workDir` every reboot will require extra complexity with a separate daemon that runs as `root` otherwise it won't have sufficient privileges.
As we clean the `workDir` when the service first starts anyway, it ends up being the same.
=> github-runners: move `workDir` outside of `/run`

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/WindowManager.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
All credits go to @AlexOwl. Their [PR](https://github.com/LnL7/nix-darwin/pull/505) looked abandonned so I reported their changes and addressed the change requests.
=> (feature) Add Stage Manager (com.apple.WindowManager) settings

modules/system/keyboard.nix, tests/system-keyboard-mapping.nix
Use this and never find yourself again hitting fn because of muscle memory! (you can even physically swap the keycaps, at least on M series)
Keycodes have been pulled from https://hidutil-generator.netlify.app/ and the hex value has been converted to a base 10 int.
(was previously opened as #991 but made a mistake)
=> (feature) Add swapLeftCtrlAndFn

modules/nix/nix-darwin.nix
A port of https://github.com/NixOS/nixpkgs/blob/50f054152e00aaee3e75b3041f666453605029bd/nixos/modules/installer/tools/tools.nix#L121
Why?
Other installer tools exist like [`nh_darwin`](https://github.com/ToyVo/nh_darwin)
=> feat: system.disableInstallerTools

README.md
Fixes #918 
This command should work on both non-flake and flake based setups as it does not require `nixpkgs` to be set in `NIX_PATH`.
Also remove the manual install section as it is unmaintained as far as I can tell.
=> Use flake based command for uninstaller in README

modules/programs/gnupg.nix
In some scenarios, the command may fail, e.g. when the shell is executed with a different $HOME from where gpg agent is configured to run from.
(E.g. this happens in kitty terminal test suite.)
This patch will suppress stderr errors on tty in this situation.
Note that zsh does not allow to suppress execution of /etc/zshenv on startup, so it's impossible to skip it in the test suite environment.
An alternative would be to set IN_NIX_SHELL in the test suite, but this was rejected in upstream:
https://github.com/kovidgoyal/kitty/pull/7800
There's also a kitty package specific fix posted here but this may be unnecessary once nix-darwin is patched here:
https://github.com/NixOS/nixpkgs/pull/338070
=> gpg: Suppress stderr from gpg-connect-agent on shell init

modules/users/group.nix
The upstream Nix UID/GID changes for Sequoia will require us to manage a group with GID 350. That will require more work on our end to ensure compatibility and a working migration path, but this is enough to allow hacking around it locally in system configurations for now.
=> users: allow arbitrary group IDs

modules/services/github-runner/service.nix
Shellcheck complains:
> args=(
>      ^-- SC2054 (warning): Use spaces, not commas, to separate array elements.
Add a comment disabling shellcheck in this case and annotating why.
=> nixos/github-runner: fix build failure

modules/programs/zsh/default.nix
Backports the following two commits from NixOS. Both are related to the way the Zsh `fpath` is being mangled:
- NixOS/nixpkgs@8dad5a22399782a4ef681174219546cb050e580f: ensures that the Zsh fpath contains entries from Nix unconditionally, even when `setopt no_global_rcs` is set in the user's `.zshenv`.
- NixOS/nixpkgs@f70e3f3738300ef1e94737c09364cd176893858f: ensures that Nix fpath entries take precedence over Zsh's ones.
=> Backport Zsh fpath mangling from NixOS

tests/networking-hostname.nix, tests/users-groups.nix
=> tests/{networking-hostname,users-groups}: update for `lib.escapeShellArg` change

.github/workflows/test.yml, CHANGELOG, modules/examples/flake/flake.nix, modules/examples/ofborg.nix, modules/examples/simple.nix, modules/misc/ids.nix, modules/system/checks.nix, modules/system/version.nix
See:
* https://github.com/LnL7/nix-darwin/issues/970
* https://github.com/NixOS/nix/issues/10892
* https://github.com/NixOS/nix/pull/11075
* https://github.com/NixOS/nix/pull/10919
* https://github.com/DeterminateSystems/nix-installer/issues/1001
* https://github.com/DeterminateSystems/nix-installer/issues/1115
* https://github.com/DeterminateSystems/nix-installer/pull/1123
* https://github.com/DeterminateSystems/nix-installer/pull/1143
* https://git.lix.systems/lix-project/lix-installer/issues/24
This is fairly subtle stuff, but also time‐critical; Apple has given us an unexpected gift by announcing that **Sequoia will release on Monday**, making it the earliest macOS release in over a decade. Currently, Nix users upgrading to Sequoia get a broken installation that outputs a useless …
=> {ids,checks}: update for new builder UID/GID values

pkgs/nix-tools/darwin-rebuild.sh
The script returns early when `$systemConfig` is empty, which currently prevents the changelog from being displayed.
Fixes #329
---
Before, `$systemConfig=`
```console
$ darwin-rebuild changelog
(nothing)
```
After, `$systemConfig=/nix/store/22dc9r5hhm311x5bffwjjr1abr3r2jrz-darwin-system-24.05.20240830.6e99f2a+darwin5.f4f18f3`:
```console
$ darwin-rebuild changelog
CHANGELOG
2024-09-10
- The default Nix build user group ID is now set to 350 when
`system.stateVersion` ≥ 5, to reflect the default for new Nix
installations. This only affects installations that enable
`nix.configureBuildUsers`, and any divergence will be detected on
system activation. To use `nix.configureBuildUsers` with a higher
`system.stateVersion` on installations using the old group ID, set:
ids.gids.nixbld = 30000;
We …
```
=> Fix darwin-rebuild changelog not displaying

flake.nix, modules/module-list.nix, modules/nix/nixpkgs-flake.nix
Backport of NixOS/nixpkgs@e456032addae76701eb17e6c03fc515fd78ad74f, which ensures that `NIX_PATH` includes `nixpkgs=flake:nixpkgs` when the system was built from a flake.
Here is the rationale for having `NIX_PATH` correctly set in a flake context, especially since Nix 2.24: https://github.com/NixOS/nixpkgs/pull/273170#issuecomment-2342254448
---
💻 **Demonstration from a REPL session, using my own system flake importing this branch**
1. Before `switch`, despite having `extra-nix-path = nixpkgs=flake:nixpkgs` in `nix.conf`:
```console
$ nix repl --expr 'import <nixpkgs> {}'
Nix 2.24.6
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
```
1. Open the REPL and load the flake's output to execute `nix-darwin.lib.darwinSystem`:
```console
$ nix repl
Nix …
```
=> Put nixpkgs in NIX_PATH and system registry for flake configs

modules/programs/bash/default.nix, modules/programs/zsh/default.nix, tests/programs-zsh.nix
The condition does not match the comment, and therefore not the original intention. It currently returns early in *any* type of Nix shell, not just pure ones, including 'nix develop'.
Besides being unnecessary, this check prevents Nix shells from functioning properly. For instance, it causes the initialization of the Zsh fpath to be skipped, which is critical. The fact that the user is unable to opt out of this behaviour makes this an ever bigger problem since /etc/zshenv is being loaded unconditionally by Zsh.
For reference, NixOS does not perform such check, and apparently never did based on my inspection of the [commit history](https://github.com/NixOS/nixpkgs/commits/nixos-24.05/nixos/modules/programs/zsh/zsh.nix).
For a history, see the following commits (without comment or context …
=> Remove nix-shell early return in /etc/{zshenv,bashrc}

modules/system/version.nix, release.nix
When testing the Sequoia UID change, I discovered that @mjm didn’t have `system.stateVersion` set; I suspect this is not too uncommon. Let’s make it required now, like NixOS is trying to, to improve our backwards‐compatibility story in anticipation of starting to cut release branches.
=> version: make `system.stateVersion` mandatory

modules/system/checks.nix
This is hopefully largely cosmetic, but should increase user confidence in the safety and effectiveness of the migration, and the Determinate Systems and Lix installer commands will also update the `/nix/receipt.json` files to match the changes made. They cannot properly handle the format of each other’s receipts, so we need to detect which was used.
=> checks: show Sequoia migration commands for other installers

modules/launchd/default.nix, modules/nix/linux-builder.nix, modules/services/karabiner-elements/default.nix, modules/services/nix-daemon.nix, modules/services/nix-optimise/default.nix, modules/services/tailscale.nix, tests/autossh.nix, tests/services-activate-system-changed-label-prefix.nix, tests/services-activate-system.nix, tests/services-buildkite-agent.nix, tests/services-lorri.nix, tests/services-nix-gc.nix, tests/services-nix-optimise.nix
Addresses my recent issue, https://github.com/LnL7/nix-darwin/issues/1043.
I've attempted to make this compatible with both the 'command' and 'script' options of 'launchd.daemons.<name>'. This works fine on my machine, but some tests that check the launchd plist files fail because this will change the format of them slightly. 
I thought I would put this first commit here in case anyone had any objections before I went ahead and rewrote all of the tests and modules to not use wait4path anymore.
=> Use wait4path with command and script launchd options

flake.nix
=> flake: match NixOS definition of `nixpkgs.flake.source`

modules/system/defaults/dock.nix
This patch was inspired by a recent [Daring Fireball post][l] where I was
reminded about this feature and how it's missing from being able to configure it
in Nix-Darwin.
The command I had run to get this working is outlined in the post & below.
```sh
default write com.apple.dock slow-motion-allowed -bool YES;
```
[l]: https://daringfireball.net/linked/2024/09/28/hidden-pref-to-restore-slow-motion-dock-minimizing-on-macos
=> Adding option for slow-motion-allowed

modules/system/defaults/dock.nix
Fixes trace warning introduced by https://github.com/LnL7/nix-darwin/pull/1094
> trace: evaluation warning: lib.mdDoc will be removed from nixpkgs in 24.11. Option descriptions are now in Markdown by default; you can remove any remaining uses of lib.mdDoc
=> fix: remove deprecated lib.mdDoc

modules/services/jankyborders/default.nix, tests/services-jankyborders.nix
Adds undocumented JankyBorders option `order` which can be set to `above` or `below`. Defaults to `below` because it causes issues for some users (hence the reason for not being documented). Helpful for covering the window frame on macos.
=> jankyborders service option order above or below

modules/services/postgresql/default.nix
`--pgdata/-D` option is missing and without it database cannot be initialised.
=> fix: postgresql service initdb

modules/system/defaults-write.nix
I'm not sure if something changed in macOS or if this ever worked (@treffynnon, who originally added this might know 🤷).
I've tried both `true` and `false` for [`system.defaults.SoftwareUpdate.AutomaticallyInstallMacOSUpdates`](https://daiderd.com/nix-darwin/manual/index.html#opt-system.defaults.SoftwareUpdate.AutomaticallyInstallMacOSUpdates) and nothing seems to change in System Settings as I would have expected it to.
I _did_ discover that there's a `/Library/Preferences/com.apple.SoftwareUpdate.plist` on my mac which _does_ appear to reflect the Software Update settings.
> `$ plutil -p /Library/Preferences/com.apple.SoftwareUpdate.plist`
```
{
"AutomaticallyInstallMacOSUpdates" => 0
"LastAttemptBuildVersion" => "14.5 (23F79)"
"LastAttemptSystemVersion" => "14.5 (23F79)" …
```
=> Use the correct file location for `SoftwareUpdate` plist.

modules/users/default.nix
`sysadminctl -deleteUser` will only prevent you from deleting the current user if it's not the last admin and not the last secure token user, otherwise it will happily oblige.
=> users: prevent deleting the user calling `darwin-rebuild`

modules/module-list.nix, modules/networking/default.nix, modules/power/default.nix, modules/power/sleep.nix, modules/system/activation-scripts.nix, tests/networking-wakeonlan.nix, tests/power-restart.nix, tests/power-sleep.nix
Hey there, I've recently picked up nix-darwin to configure a Mac Mini M2 as a home server.
I need to configure some power related options that nix-darwin currently does not offer, so I would like to contribute them.
This pull request adds:
- `networking.wakeOnLan.enable`
- `power.restartAfterPowerFailure`
- `power.restartAfterFreeze`
- `power.sleep.computer`
- `power.sleep.display`
- `power.sleep.harddisk`
- `power.sleep.allowSleepByPowerButton`
The options are implemented by means of the `systemsetup` command that also is used for the `time.timezone` option.
I believe this is the command that System Settings uses behind the screen.
I've tried to guess where it made most sense to add the new options.
I've added a new `power` module; maybe it would make more sense to place the restartXXX …
=> Power related options (sleep, wake-on-lan, restart after power failure, ...)

pkgs/nix-tools/darwin-rebuild.sh
This change updates the usage description of `darwin-rebuild.sh` as follows:
* Add options:
* `--print-build-logs` / `-L`
* `--no-registries`
* `--commit-lock-file`
* `--no-write-lock-file`
* ` --override-input`
* Specify that `--no-flake` and the flake related options are mutually exclusive.
* Specify that `--keep-going` and `-k` are aliases.
* Specify that `--keep-failed` and `-K` are aliases.
* Correct the description of `--update-input`; only one value follows.
The `--no-build-hook` argument remains undocumented, like for `nix`.
=> darwin-rebuild: Align usage description with implementation

modules/services/emacs.nix
Otherwise, the service will never recover after the daemon dies for any reason.
=> Add keepalive flag for emacs service

modules/system/activation-scripts.nix, modules/system/shells.nix, modules/users/default.nix, modules/users/user.nix, pkgs/darwin-installer/default.nix, tests/programs-zsh.nix, tests/users-groups.nix
I'm leaving `gid` and `isHidden` for later PRs
=> users: update properties for known users

modules/examples/flake/flake.nix, modules/examples/simple.nix, modules/programs/zsh/default.nix
Historically this was a footgun because users would not always have this enabled leading to `darwin-rebuild` and other programs not being found.
See #177, #922 and #1003
=> zsh: enable by default as zsh is the default shell on macOS

modules/services/karabiner-elements/default.nix
This is necessary to be able to experiment changes to the package without completely copying the module.
cc @Enzime
=> karabiner-elements: allow use of custom package

modules/environment/default.nix, modules/examples/lnl.nix, modules/programs/tmux.nix
This is a source of confusion as this option was only used to configure tmux's default command, rather than `users.users.<user>.shell` which is what most people actually wanted which wasn't working very reliably prior to #1120 
I also chose to remove `programs.tmux.defaultCommand` as I suspect that most users want it to default to their login shell and very few need to change it.
Closes #361
See #151, #779
=> environment: remove misleading `environment.loginShell` option 

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/hitoolbox.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
See values here: https://macos-defaults.com/keyboard/applefnusagetype.html
Wasn't sure if it made sense to create a file for one option but seemed okay. All com.apple.HIToolbox available options I see are:
```
"com.apple.HIToolbox" =     {
AppleCurrentKeyboardLayoutInputSourceID = "com.apple.keylayout.US";
AppleDictationAutoEnable = 0;
AppleEnabledInputSources =         (
{
InputSourceKind = "Keyboard Layout";
"KeyboardLayout ID" = 0;
"KeyboardLayout Name" = "U.S.";
},
{
"Bundle ID" = "com.apple.CharacterPaletteIM";
InputSourceKind = "Non Keyboard Input Method";
}
);
AppleFnUsageType = 2;
AppleSelectedInputSources =         (
{
InputSourceKind = "Keyboard Layout";
"KeyboardLayout ID" = 0;
"KeyboardLayout Name" = "U.S.";
}
);
};
```
=> Allow configuring the fn key action

modules/misc/ids.nix, modules/module-list.nix, modules/services/monitoring/prometheus-node-exporter.nix
This PR adds a module for the Prometheus Node Exporter, which I want to use in the nixos.org infra.
I will test this shortly, but it is probably good enough for a review.
Options are similar to [NixOS](https://search.nixos.org/options?channel=24.05&show=services.prometheus.exporters.node.extraFlags&from=0&size=50&sort=relevance&type=packages&query=exporters.node), but I chose a different namespace, since what NixOS has is probably overkill.
=> module: add prometheus-node-exporter service

.github/workflows/test.yml, .github/workflows/update-manual.yml
The `macos-12` runner image will be removed by 3 Dec 2024.
=> ci: switch to `macos-13`

modules/services/monitoring/prometheus-node-exporter.nix
The daemon won’t start as the assigned user doesn’t have permissions to create the log file.
=> prometheus-node-exporter: fix log permissions

modules/programs/zsh/default.nix
Hello,
I would like to add support for zsh-fast-syntax-highlighting which has marginally better performance than zsh-syntax-highlighting, to the zsh configuration module in nix-darwin. 
The repository can be found [here](https://github.com/zdharma-continuum/fast-syntax-highlighting)
There is an existing nix package for zsh-fast-syntax-highlighting [here](https://github.com/zdharma-continuum/fast-syntax-highlighting)
=> Add support for zsh-fast-syntax-highlighting

.github/workflows/test.yml, pkgs/darwin-uninstaller/configuration.nix, pkgs/darwin-uninstaller/default.nix
=> uninstaller: improve

modules/nix/default.nix
Upstream issue at https://github.com/NixOS/nix/issues/7273
Should be fixed by https://gerrit.lix.systems/c/lix/+/2100
Tested the version check with Nix, Lix `2.91.0` (`pkgs.lixVersions.latest`), Lix `2.92.0-devpre20241106_1ecfff9` (`github:lix-project/lix/1ecfff9c37f64871661d615e407ec3571489eff7`, doesn't include the fix) and Lix `2.92.0-devpre20241107_72cce7b` (`github:lix-project/lix`) which does include the change
Closes #484
=> nix: don't allow using `auto-optimise-store` as it can corrupt the store

modules/programs/zsh/default.nix
As of 470f87c1827b51169ed4f91cdbdfd48417bfff3d, `programs.zsh.enable` defaults to true. This means that `/etc/zshenv` has the normal nix-darwin initialization, including setting `__NIX_DARWIN_SET_ENVIRONMENT_DONE=1`.
***
On a related note, `man zsh` says:
> Commands are first read from /etc/zshenv; this cannot be overridden.
and
> As /etc/zshenv is run for all instances of zsh, it is important that it be kept as small as possible.  In particular, it is a good idea to put code that does not need to be run for every single shell behind a test of the form `if [[ -o rcs ]]; then ...` so that it will not be executed when zsh is invoked with the `-f` option.
***
Separately, when Alacritty launches a shell on macOS, [it runs the shell through three layers of …
=> zsh: only run shell initialization in /etc/zshenv when RCs are enabled

.github/workflows/update-manual.yml
This causes `nix-darwin` to not have `rev` or `dirtyRev`
=> ci: don't override nixpkgs when building the manual

modules/module-list.nix, modules/system/defaults-write.nix, modules/system/defaults/clock.nix, modules/system/defaults/controlcenter.nix, modules/system/defaults/dock.nix, modules/system/defaults/finder.nix, modules/system/defaults/screencapture.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
Adding support to control center API
=> defaults: add `controlcenter` and other options

modules/system/checks.nix
fixes #778
cc: @Enzime please recommend changes
=> feat: check if homebrew exists

README.md, modules/nix/default.nix, modules/services/activate-system/default.nix, tests/services-activate-system-changed-label-prefix.nix, tests/services-activate-system.nix
Disabling this is not supported as `/run` gets cleared out on every reboot so it is necessary for ensuring that the `/run/current-system` symlink exists.
=> activate-system: remove `enable` option

.github/workflows/test.yml, README.md, modules/examples/flake/flake.nix, modules/examples/hydra.nix, modules/examples/lnl.nix, modules/examples/simple.nix, modules/nix/default.nix, modules/services/nix-daemon.nix, modules/system/checks.nix, pkgs/darwin-installer/default.nix, pkgs/darwin-uninstaller/configuration.nix, pkgs/darwin-uninstaller/default.nix
Single user installs have been unsupported by the official Nix installer since 2.4.
=> nix-daemon: enable by default

modules/system/checks.nix
The generated user activation script is broken when NIX_PATH contains paths with spaces in them due to the spaces not being escaped.
The motivation for this fix is that I've set `use-xdg-base-directories` to `true` while also customizing the `XDG_*_HOME` variables to try and follow macOS conventions (i.e. `XDG_CONFIG_HOME` is `~/Library/Application Support`, hence the issue with spaces in the path). I then set one of the paths in `nix.nixPath` to `$HOME/Library/Application Support/nix/defexpr/channels` which causes the user activation script for switching to a new generation to break.
=> fix broken NIX_PATH if paths contain spaces

modules/system/checks.nix
With the recent addition of https://github.com/LnL7/nix-darwin/pull/961, this unintentionally broke [nix-homebrew](https://github.com/zhaofengli/nix-homebrew) see [the issue](https://github.com/zhaofengli/nix-homebrew/issues/45). Thus this PR implments `system.checks.verifyHomebrewInstall` as a way to disable the check allowing nix-homebrew to function normally if users disable it.
=> fix: allow users to disable the homebrew check

.github/workflows/test.yml
`test-stable` takes around 30 minutes now so fails fairly often now
=> ci: extend timeout and remove `tmate`

modules/system/defaults/WindowManager.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
add EnableTiledWindowMargins to WindowManager.nix to enable the ability to control margins with defaults
=> defaults: add EnableTiledWindowMargins option

modules/system/defaults-write.nix, modules/system/defaults/dock.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
Noticed option wasn't doing anything and saw it was renamed in previous macOS releases. 
Not sure why the rename trace is being triggered a couple times, I don't see it referenced anywhere.
=> defaults: expose-group-by-app -> expose-group-apps

modules/nix/default.nix
#1152 added an assertion to prevent use of `nix.settings.auto-optimise-store` on buggy versions of Nix/Lix. This check breaks with the Lix package provided by the [Lix nixos-module flake](https://git.lix.systems/lix-project/nixos-module/src/branch/main/flake.nix) as it has a different version string:
```
$ git clone https://git.lix.systems/lix-project/nixos-module && cd nixos-module
$ nix repl
Lix 2.91.1
Type :? for help.
nix-repl> :lf .
Added 18 variables.
nix-repl> packages.x86_64-darwin.default.version
"2.92.0-dev-pre20241115-c859d03"
nix-repl> packages.x86_64-darwin.default.VERSION_SUFFIX
"-pre20241115-c859d03"
```
```
$ git clone https://git.lix.systems/lix-project/lix && cd lix
$ nix repl
Lix 2.91.1
Type :? for help.
nix-repl> :lf .
Added 20 variables.
nix-repl> …
```
=> nix: fix Lix version detection in auto-optimise-store assertion

modules/services/aerospace/default.nix, tests/services-aerospace.nix
The `after-startup-command` is disabled by mistake. While it's true that the `after-login-command` doesn't work, the startup commands work just fine (see [relevant code](https://github.com/nikitabobko/AeroSpace/blob/de93349dc342175b0f8332d2db4c41c433378eb1/Sources/AppBundle/initAppBundle.swift#L30-L33))
=> fix(aerospace): allow startup commands

modules/services/github-runner/options.nix, modules/services/github-runner/service.nix
https://github.com/LnL7/nix-darwin/commit/3b738c765de1bb4ecc4993fa092b27dd46d495ed made `/var/log/github-runner` have `o=`, however the launch daemon fails to redirect stdout/stderr if the parent directory doesn't have `o=rx`, even if the inner directory has `o=rx`
=> github-runner: fix service not starting

modules/programs/ssh/default.nix
Same interface as in NixOS. This is useful to apply configuration for remote builders.
=> programs.ssh: add extraConfig option

modules/programs/zsh/default.nix
check [zsh-fast-syntax-highlighting source](https://github.com/NixOS/nixpkgs/blob/394571358ce82dff7411395829aa6a3aad45b907/pkgs/by-name/zs/zsh-fast-syntax-highlighting/package.nix#L23)
=> fix(zsh): correct the path of zsh-fast-syntax-highlighting

modules/system/defaults/screencapture.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
Adds the ability to set `com.apple.screencapture.target` default, which tells screencapture to output screenshot to e.g. clipboard. I prefer to put my screenshots directly into my clipboard, and there wasn't an option to do that through nix-darwin, so i've made the PR :)
Tested it using different valid values on Sequoia, valid values were observed by setting different "Save to" settings and reading using `defaults read com.apple.screencapture target`:
=> defaults: add screencapture.target option

modules/services/aerospace/default.nix, tests/services-aerospace.nix
trying to fix #1142
this might be redundant or even extra since i found out later that we already have #1168
fixes the error for most of my use cases not sure if there are any other issues.
let me know if there is some changes that i should make for this to be merged.
=> aerospace: add `workspace-to-monitor-force-assignment` option and fix `on-window-detected` type

modules/power/default.nix, modules/system/checks.nix
This should fix the issue reported in https://github.com/LnL7/nix-darwin/issues/1236
Changed the generated activation script fragment to check if the option is actually supported by the machine.
Also added to the option description info that the option could not work on some devices.
=> power: restartAfterPowerFailure option is carried out conditionally

modules/system/checks.nix
One of the printed string in [PR](https://github.com/LnL7/nix-darwin/pull/1241)  was triggering https://www.shellcheck.net/wiki/SC2016.
This should fix the issue.
Sorry for that, I should have checked the suggested change.
=> power: quote in string triggered shellcheck SC2016

modules/homebrew.nix
Some casks have extrenal dependencies managed by brew, neovide for examples declares neovim as a dependency, a problem arises when you want to use a nix managed neovim instead
=> Add --ignore-dependencies option for casks

modules/nix/default.nix
Backport of https://github.com/NixOS/nixpkgs/pull/318635
=> nix: merge `nix.settings.trusted-users` by default

.github/workflows/test.yml, README.md, eval-config.nix, flake.lock, flake.nix, modules/examples/flake/flake.nix, modules/system/checks.nix, modules/system/version.nix, version.json
Finally!
Once this is approved, I will cut a `nix-darwin-24.11` branch and PR the appropriate changes.
Left as future work:
* Building a seperate manual for each release, moving content from `README.md` and `CHANGELOG` to the manual, and linking an index page with the manuals for each version from `README.md`.
* Infrastructure for automated backports.
* Writing a checklist for the release process (or better, automating it).
* Perhaps having a bot automatically update our `flake.lock` so we can just tell people to use nix-darwin’s Nixpkgs input rather than bringing their own (and risking mismatches).
Closes: #727
=> Make release branches a thing

modules/system/defaults/WindowManager.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
This adds support for the following defaults:
- com.apple.WindowManager.EnableTilingByEdgeDrag
- com.apple.WindowManager.EnableTopTilingByEdgeDrag
- com.apple.WindowManager.EnableTilingOptionAccelerator
They match the top 3 settings in the screenshot under the "Desktop & Dock" page of system settings.
=> Add support for additional window tiling options

modules/system/defaults-write.nix
These are lists, not attribute sets, so the condition was always succeeding. As far as I can tell this bug has been present since the function was added.
=> defaults-write: fix activation script conditionalization

modules/system/defaults/WindowManager.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
This adds support for the following defaults:
- com.apple.WindowManager.EnableTilingByEdgeDrag
- com.apple.WindowManager.EnableTopTilingByEdgeDrag
- com.apple.WindowManager.EnableTilingOptionAccelerator
(cherry picked from commit 4075a3c23aa7996acc960e61df9f21038136d08a)
=> [24.11] Add support for additional window tiling options

eval-config.nix
Backport of https://github.com/LnL7/nix-darwin/pull/1290.
=> [24.11] eval-config: omit `enableNixpkgsReleaseCheck` from `lib.evalModules`

pkgs/nix-tools/darwin-rebuild.sh
Theoretically required for `darwin-rebuild edit -I darwin-config=…`, I guess. We also shouldn’t run it for flake‐based setups.
=> darwin-rebuild: pass `${extraBuildFlags[@]}` to `nix-instantiate`

pkgs/darwin-uninstaller/configuration.nix, pkgs/darwin-uninstaller/default.nix
Handle this now that we recommend people use `sudo nix-channel --add`. I’m not sure `~/.nix-defexpr` is always used (e.g. with XDG directories?), so we just remove it unconditionally in both user and system activation and hope the warning isn’t too bothersome, but maybe we could do something smarter here.
@Enzime I don’t suppose you have any idea what the `[[ "$(shasum -a 256 /Library/LaunchDaemons/org.nixos.nix-daemon.plist | awk '{print $1}')" == "$(shasum -a 256 /Library/LaunchDaemons/org.nixos.nix-daemon.plist | awk '{print $1}')" ]]` thing from 3a89b614321ab8dad3962d79fc3a29bace9a8486 is about?
=> darwin-uninstaller: remove `darwin` channel from `root` too

modules/system/checks.nix
Now that we create `/run` as part of activation, this is no longer useful for anaything.
=> checks: remove `runLink`

modules/nix/nix-darwin.nix, pkgs/nix-tools/darwin-option.sh, pkgs/nix-tools/darwin-rebuild.sh, pkgs/nix-tools/default.nix
I wonder if we actually want nix-darwin specific things like `/etc/profiles/per-user/$USER/bin` in the default path here. Probably it doesn’t hurt to, especially for the uninstaller, but I guess it could cause issues with reinstalling after a weird half‐uninstalled nix-darwin setup or something. It’ll refer to `root`’s packages soon enough anyway…
=> nix-tools: drop `nixPackage`, overwrite `$PATH` rather than prepending, set `$NIX_PATH`

modules/system/checks.nix
It seems like this has been broken since 26bab2fd3290b42a3df54db291f0d8775f128857 from 2018; macOS `diff(1)` does not support these arguments and the `$PATH` has been fixed since that point. Before that, it would presumably only have worked if you added GNU diffutils to `environment.systemPackages`.
Proactively notifying users about breaking changes isn’t a bad idea, but the activation script doesn’t seem like the right place for it, and as it’s non‐blocking it’s likely that even if it worked it would get drowned out by the later output anyway. I’d like to move the changelog into release notes as part of the manual, which would requires changes to this anyway. Since it’s been broken for almost seven years anyway, let’s just drop it for now and revisit later.
=> checks: remove `darwinChanges`

.github/workflows/test.yml
This was installing against the base branch, which causes annoying issues when things like the state version are bumped. It’s possible this was intentional to test the upgrade path, but it’s inconsistent with the flake installation test and keeps breaking stuff on my PRs. If we want to test the upgrade path then we could re‐add it again later in a more sophisticated manner (e.g. using the example config from the previous version).
=> ci: use the PR head as `<darwin>` for install test

modules/services/activate-system/default.nix, modules/system/activation-scripts.nix
Split off from the Plan stack; see commit messages for details.
=> {activation-scripts,activate-system}: purify environment

.github/workflows/test.yml, CHANGELOG, README.md, modules/environment/default.nix, modules/examples/flake/flake.nix, modules/examples/hydra.nix, modules/examples/lnl.nix, modules/examples/simple.nix, modules/system/checks.nix, modules/system/version.nix
Split off from The Plan stack, where it becomes more important, but a good idea anyway given our general direction and to align the default between flake‐ and channel‐based setups. This is not a breaking change thanks to the `system.stateVersion` conditional (unless anyone is looking at `environment.darwinConfig` on a flake‐based setup, which I guess is possible although seems inadvisable), so we can do it now.
=> {environment,readme}: default configuration path to `/etc/nix-darwin`

modules/services/activate-system/default.nix, modules/system/activation-scripts.nix
This shouldn’t actually be split out from the Plan because of the current use of `$HOME` in the defaults for channel‐based setups.
This reverts commit 4bff4bc8ae105dbc3a56ed5255fbde9495cbf4c1.
=> Revert "{activation-scripts,activate-system}: purify environment"

modules/system/checks.nix
In `modules/system/checks.nix`, `sw_vers` is called with `--productVersion`, but the correct parameter syntax is `-productVersion`.
=> checks: fix sw_vers parameter for macOSVersion

.git-blame-ignore-revs, modules/nix/nixpkgs.nix
Should fix the module after recent Nixpkgs changes.
=> nixpkgs: backports from upstream

modules/users/default.nix
See commit messages for details.
=> users: use `launchctl managername` to determine session type

modules/nix/nixpkgs.nix
This was reverted upstream in 0b47fba23078cc01251b136c7af0127abd57112b.
This reverts commit 7c72c013b160627540b8b465a05ba258f47a16d8.
---
Keeping the module in sync with NixOS. This should only be merged once https://nixpk.gs/pr-tracker.html?pr=379615 is green on all channels, since otherwise it’ll break people’s systems again.
=> Revert "nixpkgs: make config.nixpkgs.{buildPlatform,hostPlatform} write only"

modules/homebrew.nix
Currently, setting `homebrew.masApps` causes `"mas"` to automatically be added to `homebrew.brews`. Users who want to use Homebrew only for managing App Store apps and casks, like me, can override this by setting `homebrew.brews = lib.mkForce [ ];` and adding Nixpkgs’ `mas` to their `environment.systemPackages`.
When the activation script path no longer depends on the built configuration’s `environment.systemPackages`, this will no longer work. Since this was originally added before `mas` was packaged in Nixpkgs and we now have a perfectly serviceable binary package, we can add it to the `$PATH` when invoking Homebrew and skip the automatic formula installation.
As the Homebrew `bin` directory still comes first, users who specifically want the formula can restore the previous behaviour by …
=> homebrew: use `mas` from Nixpkgs

modules/nix/default.nix
Fixes #626.
Essentially a copy of NixOS's workaround: https://github.com/NixOS/nixpkgs/pull/278064
Nix has somewhat surprising semantics when `extra-`prefixed settings are used in the same file as their non-prefixed siblings. Any `extra-`prefixed setting is ignored if it is placed _before_ its respective non-prefixed setting.
Add an extra substituter to your config:
```nix
{
nix.settings.extra-substituters = [
"https://devenv.cachix.org"
];
}
```
The `nix.conf` in `/etc/nix/nix.conf` will be sorted alphabetically:
```
...
extra-substituters = https://devenv.cachix.org
...
substituters = https://cache.nixos.org
```
Verify that the extra substituter is missing with `nix config show`.
Nix ignores the `--extra`-prefixed keys if they're followed by their non-prefixed siblings, as documented in …
=> nix: place `extra-`prefixed settings after their non-prefixed variants

modules/nix/default.nix, modules/nix/linux-builder.nix, modules/nix/nix-darwin.nix, modules/nix/nixpkgs-flake.nix, modules/services/activate-system/default.nix, modules/services/cachix-agent.nix, modules/services/github-runner/service.nix, modules/services/hercules-ci-agent/default.nix, modules/services/lorri.nix, modules/services/nix-gc/default.nix, modules/services/nix-optimise/default.nix, modules/services/ofborg/default.nix, modules/system/activation-scripts.nix, tests/nix-enable.nix
Things that expect a managed Nix installation should have a corresponding assertion so that we don’t incorrectly use the default `nix.package` when the user has opted out of Nix management or otherwise interfere with use of an unmanaged system Nix. NixOS had some of these checks already but I didn’t catch them when backporting the functionality in the initial PR; others are in modules only present in nix-darwin, or else should probably be upstreamed to NixOS at some point. Also fix some miscellaneous other bugs where we were incorrectly using the managed defaults or assuming the guaranteed presence of an active Nix installation even when `nix.enable` was turned off. See commit messages for more details.
---
**Note:** This work was funded by Determinate Systems.
=> treewide: add checks for `nix.enable`

modules/system/defaults/dock.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
You can create spacer tiles in the dock by passing empty tile-data with specific tile-types.
Used to do this in my old dotfiles and have been meaning to upstream a change to support doing this in nix-darwin.
=> dock: allow setting spacer tiles

.github/workflows/test.yml, doc/known-files/c7dd0e2ed261ce76d76f852596c5b54026b9a894fa481381ffd399b556c0e2da, modules/networking/default.nix, release.nix, tests/networking-hosts.nix
This code was taken nearly verbatim from
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/config/networking.nix
The few changes were related to making the default `/etc/hosts` match the Apple's stock one. This implied no `127.0.0.2` and forcing the IPV6 `::1` entry.
=> Add networking.hosts and .hostFiles from nixos 

modules/security/pam.nix
Supersedes #1020, #591, #787 and #662
Closes #784 and #985
=> fix: move `pam` configuration to `sudo_local`

modules/security/pam.nix
With projects like [pam-watchid](https://github.com/Logicer16/pam-watchid), it's now possible to enable apple watches to authenticate `sudo` commands, alongside with `TouchID`. This is mostly a raw idea, but I would love to see something like this in `nix-darwin`.
Because this is used to present an idea, there are couple things to note:
1. I did not add any tests
2. I straight up embedded a package in the source code
3. The `x86` part fails to compile for some reason so that's now commented out so I'll need some help with that
I would love for others to pick this up as this is my first time contributing to the project, and I am unfamiliar with:
1. How to use apple's toolchains when building packages
2. Which packages should I include
3. The best practices
=> Add `pam-watchid` authentication to `sudo` command

modules/misc/ids.nix, modules/module-list.nix, modules/services/dnscrypt-proxy.nix, release.nix, tests/services-dnscrypt-proxy.nix
Hello!
I have been using [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy/tree/master) with nix-darwin on my own configuration. I just want to start contribution in nix-darwin.
Thank you
=> services/dnscrypt-proxy: init

modules/services/dnscrypt-proxy.nix
`dnscrypt-proxy2` is just an alias for `dnscrypt-proxy`. Use that and avoid eval failures when Nixpkgs is configured with `allowAliases = false`.
=> services/dnscrypt-proxy: Fix use of pkg alias

modules/homebrew.nix
backport of #1362
(cherry picked from commit 991bb2f6d46fc2ff7990913c173afdb0318314cb)
closes #1363
=> [24.11] homebrew: remove --no-lock flag

modules/services/nextdns/default.nix
Following up on #1052, I updated the nextdns service to use `command` in order for it to wait for the nix store to be available.
=> Update nextdns to use `command`

modules/users/default.nix
This pull request fixes an inconsistency I've found between NixOS and Nix Darwin.
```nix
{
users.users.myUser = {
name = "actual_name";
};
}
```
On NixOS this code will create the folder `/etc/profiles/per-user/actual_name` whereas on nix-darwin it creates `/etc/profiles/per-user/myUser`. This causes problems with certain modules in home-manager for example, which expects the `actual_name` folder to exist.
=> fix: use correct username for profile

modules/system/defaults/CustomPreferences.nix, tests/fixtures/system-defaults-write/activate-user.txt, tests/system-defaults-write.nix
Without this, custom user preferences defined in different modules for the same domain aren't merged.
For example, the following config results in only `UniversalSearchEnabled` defined:
```
{
imports = [
{
system.defaults.CustomUserPreferences = {
"com.apple.Safari"."NSUserKeyEquivalents"."Quit Safari" = "@~q";
};
}
{
system.defaults.CustomUserPreferences = {
"com.apple.Safari"."UniversalSearchEnabled" = false;
};
}
];
}
```
=> Fix merging of system.defaults.CustomUserPreferences

modules/services/github-runner/service.nix
This backs out commit 3b738c765de1bb4ecc4993fa092b27dd46d495ed.
Setting a `umask` made the parent directory have too conservative of permissions making it so `_github-runner` couldn't access the child directories.
=> Back out "github-runner: replace `mkdir -p -m` with `umask`"

modules/system/version.nix
This option applies to nix-darwin.
=> Docs: Fix references to NixOS

eval-config.nix
expose extendModules
implementation reference is https://github.com/nix-community/home-manager/blob/3142bdcc470e1e291e1fbe942fd69e06bd00c5df/modules/default.nix#L43
ref: https://github.com/LnL7/nix-darwin/pull/777
ref: https://github.com/LnL7/nix-darwin/issues/609
=> Expose `extendModules` attr

CHANGELOG, README.md, doc/manual/default.nix, eval-config.nix, modules/examples/flake/flake.nix, modules/system/checks.nix
To be merged after the [repository is moved](https://github.com/LnL7/nix-darwin/issues/1394).
=> treewide: point to the new GitHub organization

modules/nix/linux-builder.nix
As discussed in #1397
* the name of the working directory of the linux builder is not consistent with the package name
* the linux builder leaves behind state outside of the `/nix/store` when disabled
This tries to solve both by upgrading the old name and removing the directory when the module is disabled.
This doesn't handle updating to the new version and disabling at the same time. Those people might end up with an extra directory, but that is no worse than it is now, which is why I didn't want to take up the extra complexity.
@Enzime  What do you think?
=> Linux builder: working directory rename and cleanup

modules/services/monitoring/netdata.nix
For me netdata could not start unless added cache directory:
```logs
time=2025-03-18T21:27:21.023+02:00 comm=netdata source=daemon level=info errno="2, No such file or directory" tid=257369  msg="CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults."
time=2025-03-18T21:27:21.024+02:00 comm=netdata source=daemon level=alert errno="2, No such file or directory" tid=257369  msg="Cannot create required directory '/var/cache/netdata'"
0   netdata                             0x0000000104845cb0 netdata_logger_fatal + 356
1   netdata                             0x00000001044d8734 verify_or_create_required_directory + 84
2   netdata                             0x00000001044d718c set_global_environment + 524
3   netdata …
```
=> services/netdata: add cacheDir option

modules/networking/default.nix, tests/networking-hostname.nix
https://github.com/NixOS/nixpkgs/blob/f675531bc7e6657c10a18b565cfebd8aa9e24c14/nixos/modules/tasks/network-interfaces.nix#L580-L618
=> networking: backport `domain`, `fqdn` and `fqdnOrHostName` options

modules/module-list.nix, modules/programs/_1password-gui.nix, modules/programs/_1password.nix
Based on @reckenrode's configs: https://github.com/reckenrode/nixos-configs/blob/22b8357fc6ffbd0df5ce50dc417c23a807a268a2/modules/by-name/1p/1password/darwin-module.nix
I didn't add any tests as these packages are unfree and I didn't think there's enough functionality worth testing here
The option names are to match NixOS, ideally the CLI module should probably be `programs._1password-cli` but we'll just wait for upstream on that
Fixes https://github.com/NixOS/nixpkgs/issues/254944
=> programs/_1password{,-gui}: init modules

modules/services/buildkite-agents.nix
This is essentially a port of https://github.com/NixOS/nixpkgs/pull/120209.
[#653](https://github.com/nix-darwin/nix-darwin/pull/653/files#diff-b19c4de0b41d99a49a7abbfa4676f8b82f48e99ffdc697dc10788a5e74ce9104R81) already used the correct option type, just the implementation was lacking.
=> services/buildkite-agents: support multi-tags

modules/services/openssh.nix, release.nix, tests/services-openssh.nix
Same interface as in NixOS: https://search.nixos.org/options?channel=unstable&show=services.openssh.extraConfig&from=0&size=50&sort=relevance&type=packages&query=services.openssh.extraConfig
This is useful to customize the behavior of the SSH daemon, e.g. to add
options like `StreamLocalBindUnlink yes` to improve gpg-agent
forwarding.
Signed-off-by: squat <lserven@gmail.com>
=> feat(services.openssh): add extraConfig option

modules/system/default.nix
=> [24.11] `system.build`: Treat as variables, make lazy, fix error message

flake.lock
The CI failure [here](https://github.com/DeterminateSystems/flakehub-mirror/actions/runs/15220692944/job/42815651292) indicates that the `flake.lock` is currently out of date in the `nix-darwin-25.05` branch. I updated it using a standard `nix flake show` operation.
=> Update flake.lock in nix-darwin-25.05 branch

modules/config/system-path.nix, modules/environment/default.nix, modules/module-list.nix, modules/system/default.nix
I've created a new module `config/system-path` and moved a bunch of options into it to mirror NixOS:
https://github.com/NixOS/nixpkgs/blob/2795c506fe8fb7b03c36ccb51f75b6df0ab2553f/nixos/modules/config/system-path.nix
I didn't backport `requiredPackages` as it seems like `nix-darwin` doesn't have any currently unlike NixOS.
I've cherry picked this commit out of #1480
=> config/system-path: restructure to mirror NixOS

pkgs/nix-tools/darwin-rebuild.sh
(cherry picked from commit d23a9c26f37ce6600e452099ee86c916bf51ef87)
=> [25.05] darwin-rebuild: use `NIX_REMOTE=daemon` even as `root`

modules/programs/zsh/default.nix, tests/programs-zsh.nix
We got `enableSyntaxHighlighting`, so why not `enableAutosuggestions` too?
Ref: #527
I have added tests too.
However, I saw the other "plugin" related options for `zsh` are NOT tested.
Should I remove my tests for any reasons? e.g. resource concern
=> feat: add option programs.zsh.enableAutosuggestions

modules/system/primary-user.nix
(cherry picked from commit 7c284a650484c90cf928779d77d9faa3f173522e) from https://github.com/nix-darwin/nix-darwin/pull/1499 as requested by @emilazy
=> [Backport 25.05] Avoid confusing users with future deprecations

modules/homebrew.nix
Some systems set `secure_path` in sudoers. When this is set
the `PATH` variable is not set in the sudo environment. Using
`--preserve-env=PATH` and wrapping the call with `env` ensures that the PATH env var is set properly in those systems.
This is similar to the issue with [darwin-rebuild](https://github.com/nix-darwin/nix-darwin/issues/798) not working with sudo on these systems.
=> Preserve `PATH` variable when using `sudo` for Homebrew

modules/homebrew.nix
- Replace deprecated `homebrew/cask-fonts` (https://github.com/Homebrew/brew/commit/773dbfa92a2e948503918e3f5cb4769eeb584bee) tap example with [`apple/apple`](https://github.com/apple/homebrew-apple)
- Update documentation links from archived [homebrew-bundle](https://github.com/Homebrew/homebrew-bundle) repository to [brew.sh/Brew-Bundle-and-Brewfile](https://docs.brew.sh/Brew-Bundle-and-Brewfile)
- Update `brew bundle` source file references to reflect new location in main brew repository at [https://github.com/Homebrew/brew/tree/master/Library/Homebrew/bundle](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/bundle)
The `homebrew/cask-fonts` tap was deprecated and archived. This PR updates the example to use a currently maintained tap …
=> Remove deprecated homebrew tap example (homebrew/cask-fonts)

modules/homebrew.nix
Specifying the `--greedy` flag with `brew upgrade` for each cask has to be done on an opt-in basis for each cask specified in `homebrew.casks`, which can be rather tedious.
This adds an option called `homebrew.greedyCasks` that sets the default value for the `homebrew.casks.*.greedy` option, so that all casks can be changed to be greedy at once, without needing to set that option for each cask. Opting out of `--greedy` by setting it to `false` per-cask when using this option is possible as well.
Closes #572, #1201.
=> homebrew: allow setting greedy for all casks by default

modules/module-list.nix, modules/networking/applicationFirewall.nix, modules/system/defaults-write.nix, modules/system/defaults/alf.nix
This PR adds a new module `networking.applicationFirewall` for configuring the Application Layer Firewall.
=> networking.applicationFirewall: init

README.md
Changes: 
* Bump nix stable in documentation from 24.11 to 25.05.
* Update flake guide 
* Recommend users to check if hostPlatform is set right for Intel or Apple Silicon.
=> readme: bump nixpkgs stable version; update flake guide

.github/workflows/test.yml
The runners from macOS 14 on default to aarch64, so this will also transition us away from x86_64
=> ci: bump macOS version (13 -> 14)

modules/launchd/default.nix, modules/launchd/launchd.nix, modules/services/karabiner-elements/default.nix, modules/system/defaults-write.nix, tests/fixtures/system-defaults-write/system.txt, tests/fixtures/system-defaults-write/user.txt, tests/system-defaults-write.nix
**Change**
NixOS/nixpkgs#356502 introduced an argument `escape` to `lib.generators.toPlist` which makes it escape special characters in the XML. This PR makes nix-darwin use it everywhere.
This is a breaking change, as [discussed under the original PR](https://github.com/nixos/nixpkgs/pull/356502#issuecomment-2480637115).
**Rationale**
The fact that contents aren't escaped by default is [rather unintuitive](https://discourse.nixos.org/t/correctly-running-cloned-flake/55960/11), especially when an API consumer isn't even aware that their input is being used to generate XML.
=> launchd+defaults: Escape XML generated by toPlist

modules/system/applications.nix
This is a draft, because I do not yet have an option to actually test these changes, and I don't want switch my personal machine to nix-darwin@master.
I hope however, that this can be a start to get the ball rolling on a better story to install GUI applications with nix-darwin.
All existing attempts fell short.
So we fall back to plain old copying applications over.
Problems with alternatives:
- Symlinking: Spotlight doesn't index symlinks. Therefore one cannot use
Spotlight to find or open the apps. Also they don't show up in
LaunchPad.
- Trampolines: Apples Security & Privacy doesn't get the concept and
shows them with the wrong name. Having an app open during an update will
also make it show up twice in the Dock.
- Aliasses: Require either AppleScript (a permission we don't want to …
=> Application 'linking' done right

modules/launchd/launchd.nix
Fixes https://github.com/nix-darwin/nix-darwin/issues/1578
=> `apply` should return `null` if the argument is not a list

modules/services/github-runner/service.nix, tests/services-github-runners.nix
The conditional override was intended to be backwards-compatible with older runner packages without the `nodeRuntimes` argument. However, `override` doesn't yield default arguments, so the override was never applied.
This commit removes the conditional entirely since `nodeRuntimes` was added back in 24.05.
GitHub's policy is to deprecate all previous releases 30 days after a new release. In theory, this should be safe to backport to 25.05.
=> github-runner: fix the nodeRuntimes option

modules/services/github-runner/service.nix, tests/services-github-runners.nix
The conditional override was intended to be backwards-compatible with older runner packages without the `nodeRuntimes` argument. However, `override` doesn't yield default arguments, so the override was never applied.
This commit removes the conditional entirely since `nodeRuntimes` was added back in 24.05.
(cherry picked from commits f910ac37b62f28ef613b2947c27f34359ceb9f41 and 165ff3069d0f75961e8e3f51461a3ffc1458f453)
Backport of #1582.
=> [25.05] github-runner: fix the nodeRuntimes option

modules/system/defaults/NSGlobalDomain.nix
Add `NSStatusItemSpacing` and `NSStatusItemSelectionPadding` to `NSGlobalDomain` options.
These options control the spacing between and padding inside status icons in the menu bar. With these options, it's possible to squeeze more items on the menu bar, something that's especially useful on machines with a notch.
This is a copy of #872, which was closed without being merged.
=> defaults: add `NSGlobalDomain.NSStatusItem{Spacing,SelectionPadding}`
