default.nix
modules/programs/fish.nix

This is working well enough for me to use locally now, so I figured I'd open a PR. If nothing else, we can discuss publicly here.
Closes #3

Add programs.fish

---

bootstrap.sh

Figured I'd spend a little time this evening writing a bash script to bootstrap `nix-darwin`.  
It follows the steps from the README, except it uses `curl` and `unzip` to fetch the repo.  
Straightforward stuff, see what you think @LnL7 🙂

Bootstrap script

---

default.nix
modules/networking/default.nix
modules/system/activation-scripts.nix

The idea is to follow: https://nixos.org/nixos/options.html#networking so we can
share even more configuration ideas from NixOS.
@LnL7 do you think this makes any sense?

Adds an idea for networking module

---

modules/networking/default.nix

Set NetBIOS name with hostName

---

modules/system/defaults/NSGlobalDomain.nix
tests/system-defaults-write.nix

As per title.
- ordered them alphabetically for easier browsing
- added tests for each of them.

Adds more NSGlobalDomain options + tests

---

default.nix
modules/services/privoxy/default.nix
release.nix
tests/services-privoxy.nix

This adds a [privoxy](https://www.privoxy.org/) service.
Thanks for nix-darwin! 😄

Add a privoxy service

---

README.md

Remove Security link from README

---

modules/system/defaults/NSGlobalDomain.nix
modules/system/defaults/trackpad.nix

This PR adds some extra configs to defaults that I found useful.

Add defaults configs

---

modules/services/postgresql/default.nix

mostly copied from the NixOS module, tested with some plugins and seems to be working

postgresql: Add support for extraPlugins

---

modules/examples/lnl.nix
modules/module-list.nix
modules/services/hercules-ci-agent/default.nix
modules/services/ofborg/default.nix

- tests will follow in next weeks as I need to rework them a bit

Add hercules-ci-agent

---

pkgs/darwin-installer/default.nix

darwin-installer: use --show-trace

---

modules/programs/bash/default.nix

Fixes https://github.com/LnL7/nix-darwin/issues/101

Let bash load completions lazily

---

modules/module-list.nix
modules/system/defaults-write.nix
modules/system/defaults/NSGlobalDomain.nix
modules/system/defaults/SoftwareUpdate.nix
modules/system/defaults/alf.nix
modules/system/defaults/loginwindow.nix
modules/system/defaults/spaces.nix

This PR includes a load more default system settings for osx that allow the configuration of the mentioned aspects

[system.defaults] more sound, firewall/alf, spaces, loginwindow, SoftwareUpdate

---

modules/environment/default.nix
modules/programs/bash/default.nix

This fixes bash completion for me, though it may not be the best way.
Hopefully this isn't too crazy or someone can tell me how to do it better. I'm very new to nix. Thanks!

Fix Bash Completions

---

modules/module-list.nix
modules/services/yabai/default.nix
release.nix
tests/services-yabai.nix

Hi again @LnL7  👋   
Here's a new service for your consideration :) I've been using this module personally for quite some time. Since you merged my yabai package PR the last week, it looks like it's now generally available in the `nixpkgs-unstable` channel - so I figured I'd get this submitted.  
This supersedes #176 
Let me know if there's any changes you want to see

module: add yabai service

---

modules/module-list.nix
modules/services/spacebar/default.nix
release.nix
tests/services-spacebar.nix

Another service for your consideration :) This is to acompany this PR in NixOS/nixpkgs#86556  
Once that package is generally available in the channels, the tests included in these changes should pass

module: add spacebar service

---

modules/system/defaults/finder.nix

Adds com.apple.finder CreateDesktop defaults to enable/disable desktop

---

modules/module-list.nix
modules/services/lorri.nix
release.nix
tests/services-lorri.nix

I was working in parallel to this pr #204 and managed to make it work. I open a new pull request as it was easier to add my changes here.

Adds Lorri module

---

modules/system/defaults/NSGlobalDomain.nix
tests/system-defaults-write.nix

👋 Hey there!
I verified the following on Catalina via
```sh
darwin-rebuild switch -I darwin=.
```
Also corresponding lines to the appropriate test.

Add options for MacOS swipe navigation

---

modules/module-list.nix
modules/services/nextdns/default.nix
release.nix
tests/services-nextdns.nix

I didn't know I needed to add nextdns to a modulelist.
I kept on wondering why it wasn't working.
Sorry about that!

nextdns: add to modulelist

---

modules/module-list.nix
modules/services/spotifyd.nix
release.nix
tests/services-spotifyd.nix

Hi:
I added a [`spotifyd`](https://github.com/spotifyd/spotifyd) service

spotifyd: add spotifyd service

---

README.md

Resolve https://github.com/LnL7/nix-darwin/issues/336#issuecomment-868720301

Add manual install command to create symlink after 10.15 Catalina

---

modules/module-list.nix
modules/services/monitoring/telegraf.nix

Inspired by the nixos Telegraf module, with added support for config urls

telegraf: init module

---

modules/module-list.nix
modules/services/netbird.nix

Port netbird module from NixOS: https://github.com/NixOS/nixpkgs/pull/186669

Add netbird module

---

modules/launchd/launchd.nix

Fix launchd options description oddities

---

README.md

Update readme to point to Matrix instead of IRC

---

modules/launchd/launchd.nix
modules/module-list.nix
modules/services/karabiner-elements/default.nix

PR adding Karabiner-Elements to nixpkgs: https://github.com/NixOS/nixpkgs/pull/188129

Karabiner-Elements

---

modules/examples/flake.nix
modules/examples/lnl.nix
modules/fonts/default.nix
modules/security/sandbox/default.nix
modules/system/etc.nix
modules/system/launchd.nix
modules/system/patches.nix

Continuation of #535, but fixing the name of Nix.

Fix nix-darwin with recent nixpkgs

---

modules/nix/default.nix

Copied directly from https://github.com/NixOS/nixpkgs/pull/193404

nix: fix mandatoryFeatures in nix.buildMachines

---

README.md
flake.lock

update flake example in readme and flake.lock

---

modules/module-list.nix
modules/services/wg-quick.nix

This PR adds a module for wg-quick config that is analogous to the one in nixpkgs.
~~Marked as draft for now as I haven't tested everything and there's probably still some stupid typos that need to be fixed.~~

Add wg-quick module

---

pkgs/nix-tools/darwin-rebuild.sh

Hi,
this PR is basecly like #310 but with latest master.

Rebuild flake no out link, like #310 but with latest master

---

modules/services/karabiner-elements/default.nix

Improve Karabiner-Elements installer reliability

---

modules/system/defaults-write.nix

feat: support writing arrays to system defaults

---

modules/system/checks.nix
modules/system/flake-overrides.nix

flakes: Do not verify channels when using flakes.

---

modules/module-list.nix
modules/services/ipfs.nix

Adds a module for ipfs daemon.
- https://ipfs.io
- https://github.com/ipfs/kubo

add ipfs service

---

modules/system/defaults/NSGlobalDomain.nix
tests/system-defaults-write.nix

The option location: System Settings - Desktop & Dock - Windows & Apps - Prefer tabs when opening documents

feat: add `AppleWindowTabbingMode` option

---

modules/system/defaults/NSGlobalDomain.nix
tests/system-defaults-write.nix

The option location: System Settings - Appearance - Click in the scroll bar to

Add `AppleScrollerPagingBehavior` option

---

modules/system/defaults/universalaccess.nix
tests/system-defaults-write.nix

See https://developer.apple.com/documentation/devicemanagement/accessibility#:~:text=mouseDriverCursorSize

Add `mouseDriverCursorSize` option

---

.github/workflows/update-manual.yml
README.md

Fix https://github.com/LnL7/nix-darwin/issues/709.

ci: update manual updater to 23.05

---

pkgs/darwin-uninstaller/configuration.nix

uninstaller: fix removing `/Applications/Nix Apps`

---

flake.nix
modules/examples/flake/flake.nix
modules/examples/lnl.nix
modules/nix/nix-darwin.nix
modules/system/default.nix
modules/system/version.nix
pkgs/nix-tools/darwin-rebuild.sh
pkgs/nix-tools/darwin-version.sh
pkgs/nix-tools/default.nix

Adapted from https://github.com/NixOS/nixpkgs/blob/3b5456608a680a0cf7e488c7ddd250b6fef3eac1/nixos/modules/installer/tools/nixos-version.sh
Fixes #327

Add `darwin-version` command

---

modules/services/eternal-terminal.nix

See https://github.com/LnL7/nix-darwin/pull/745#discussion_r1272806159

eternal-terminal: enable keep alive

---

modules/system/defaults/dock.nix

- add dock icon magnification settings

Dock icon magnification settings

---

modules/module-list.nix
modules/services/sketchybar/default.nix

sketchybar: init

---

modules/nix/linux-builder.nix

linux-builder: add maxJobs option

---

release.nix
tests/checks-nix-gc.nix
tests/nixpkgs-overlays.nix
tests/services-nix-daemon.nix
tests/services-nix-gc.nix
tests/sockets-nix-daemon.nix

`set -e` does not trigger on negations, so none of these were actually being tested (and one appears to have been incorrectly negated all along).

tests: fix uses of `!`

---

pkgs/darwin-installer/default.nix

Just my 2 cents w.r.t. https://github.com/LnL7/nix-darwin/issues/2.
Feel free to accept / reject.

chore(installer): capitalize the default option when reading user input

---

modules/homebrew.nix

Implemented in response to changes made in, and discussion on, #765. 
Using `extraFlags` as the option name, since it's a [common convention](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=extraFlags) in `nixpkgs` for NixOS options.
CC: @tnxz, @Enzime

Add `homebrew.onActivation.extraFlags` option

---

modules/services/yabai/default.nix

Hey there, I've recently picked up nix to configure a MacBook and was setting up yabai with nix-darwin when I noticed that the yabai scripting addition was not configured properly. See [[here in the yabai install wiki]](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition).
> yabai uses the macOS Mach APIs to inject code into Dock.app; this requires elevated (root) privileges. You can configure your user to execute yabai --load-sa as the root user without having to enter a password. To do this, we add a new configuration entry that is loaded by /etc/sudoers.
This PR will allow admins to execute `yabai --load-sa` as the root user without having to enter a password.
This should partly fix #750. However, I have found that I still need to …

[yabai] Configure scripting addition

---

doc/known-files/9d5aa72f807091b481820d12e693093293ba33c73854909ad7b0fb192c2db193
modules/system/shells.nix

etc: add known hash for `/etc/shells`

---

modules/system/defaults/GlobalPreferences.nix

Use native floats for mouse scaling

---

modules/system/defaults/universalaccess.nix
tests/system-defaults-write.nix

Adding config to manage `reduce motion` option:
https://support.apple.com/guide/mac-help/stop-or-reduce-onscreen-motion-mchlc03f57a1/mac

Add `universalaccess.reduceMotion` option

---

modules/system/defaults/NSGlobalDomain.nix
tests/system-defaults-write.nix

This is just a rebased version of https://github.com/LnL7/nix-darwin/pull/513
Credit to @2gn

defaults: Add options for dragOnGesture feature

---

doc/manual/default.nix

as it got removed in https://github.com/NixOS/nixpkgs/pull/295847

Remove override.css

---

modules/module-list.nix
modules/services/nix-optimise/default.nix
modules/system/checks.nix
release.nix
tests/services-nix-optimise.nix

Add `nix.optimise` based of NixOS module. Implementation in `nix-darwin` based of `nix.gc`.
Would appreciate a sanity check on changes to `module/system/checks.nix` in particular since I'm least certain about that.

Add `nix.optimise` module

---

modules/environment/default.nix
tests/environment-path.nix

See commit messages for details.

environment: Adjust systemPath order to allow injecting in the middle

---

modules/programs/direnv.nix
modules/services/github-runner/options.nix
modules/services/sketchybar/default.nix

Removed deprecation that is incoming in Nix 25.05

chore: remove mkpackageoptionmd deprecation

---

modules/environment/default.nix
modules/nix/default.nix
modules/programs/info/default.nix
modules/system/checks.nix

Allow disabling channels

---

.github/FUNDING.yml

.github: add sponsorship details

---

modules/nix/linux-builder.nix

This allows users to access the correct values through `nix.linux-builder.package.nixosConfig` e.g.
```nix
{
nix.linux-builder.config.services.tailscale.enable = true;
}
```
```
$ nix eval github:Enzime/dotfiles-nix#darwinConfigurations.chi.config.nix.linux-builder.package.nixosConfig.services.tailscale.enable
false
$ nix eval github:Enzime/dotfiles-nix#darwinConfigurations.chi.config.nix.linux-builder.package.nixosConfig.services.tailscale.enable --override-input nix-darwin github:Enzime/nix-darwin/linux-builder-apply
true

linux-builder: make `package.nixosConfig` accurate

---

modules/system/checks.nix

checks.nix: fix typo

---

.github/workflows/update-manual.yml

https://github.com/LnL7/nix-darwin/pull/1069#discussion_r1753084948

ci/update-manual: use Nixpkgs 24.05

---

modules/system/defaults/NSGlobalDomain.nix
modules/system/defaults/dock.nix
modules/system/defaults/finder.nix
tests/fixtures/system-defaults-write/activate-user.txt
tests/system-defaults-write.nix

I missed these two options myself and added them in my fork but would like to merge them into the main repo:
- `finder._FXSortFoldersFirst`
- `NSGlobalDomain.AppleSpacesSwitchOnActivate`
Any feedback is warmly welcome. Thank you for your work!

Adjust default options

---

modules/services/karabiner-elements/default.nix

- command needed to be quoted
- resolves https://github.com/LnL7/nix-darwin/issues/1092
- works when tested on my machine. would be good if someone who had this issue could also give it a spin

fix: karabiner elements virtualhiddeviceclient error

---

modules/module-list.nix
modules/services/monitoring/netdata.nix
release.nix
tests/services-netdata.nix

feat: add netdata service

---

modules/examples/hydra.nix
modules/examples/lnl.nix
modules/nix/default.nix
modules/programs/bash/default.nix

a port of https://github.com/NixOS/nixpkgs/pull/291552 for darwin

programs/bash: move to completion.*

---

modules/networking/default.nix
modules/users/default.nix
modules/users/group.nix
modules/users/user.nix
pkgs/nix-tools/darwin-rebuild.sh
tests/networking-networkservices.nix
tests/users-groups.nix

Extracted from #1017
This should be PR should be a no-op

Use `sysadminctl` instead of `dscl`

---

modules/users/default.nix

users: don't check home directory is correct before creating user

---

modules/time/default.nix

https://www.shellcheck.net/wiki/SC2143
For https://github.com/LnL7/nix-darwin/pull/1139.

time: shellcheck fix

---

flake.nix
release.nix

Continuation of #1124 
This is useful for https://search.nüschtos.de/
@SuperSandro2000 let me know if this is sufficient or if more changes are necessary to be able to consume this package

flake: expose docs on Linux as well

---

README.md
pkgs/darwin-installer/default.nix

readme: small improvements

---

doc/manual/default.nix
doc/manual/redirects.json

manualHTML: support --redirects option in nixos-render-docs

---

modules/programs/fish.nix

I want to start testing the new beta and this override seems necessary for full testing.

fish: add package option

---

.github/workflows/test.yml
README.md

This will also let me remove a Python 3.11 workaround in #1205 :)

ci, readme: update stable nixpkgs to 24.11

---

.github/workflows/test.yml
flake.lock
flake.nix
modules/examples/flake/flake.nix
version.json

The first release branch, and presumably the only one that will go back in time.

nix-darwin 24.11

---

modules/system/base.nix
modules/system/checks.nix
modules/system/defaults/universalaccess.nix
pkgs/darwin-uninstaller/default.nix
pkgs/nix-tools/darwin-rebuild.sh

To be merged after https://github.com/LnL7/nix-darwin/pull/1259 to align with Nixpkgs 25.05’s support.

checks: check for macOS ≥ 11.3

---

README.md

Closes https://github.com/LnL7/nix-darwin/issues/1349

readme: update instructions as Determinate Nix is now the default

---

.github/workflows/test.yml
CHANGELOG
README.md
doc/manual/default.nix
eval-config.nix
modules/examples/flake/flake.nix
modules/system/checks.nix

[24.11] treewide: point to the new GitHub organization

---

doc/website/index.html
flake.nix

My excuse for testing in prod is that GitHub Actions makes it a pain to do anything else.

website: try to fix

---

modules/nix/nix-darwin.nix
pkgs/nix-tools/default.nix

nix-tools: re‐add `nixPackage`

---

modules/networking/default.nix

Backport of https://github.com/NixOS/nixpkgs/pull/391522

networking: allow users to override FQDN

---

flake.lock
pkgs/nix-tools/default.nix

nix-tools: use replaceVarsWith

---

modules/system/defaults/NSGlobalDomain.nix

Eventually we should implement a special type that allows deleting values.

defaults: update docs for `AppleInterfaceStyle`

---

CHANGELOG
modules/system/default.nix
modules/system/primary-user.nix

Just updated after #1341 and noticed the old link in the error message.

Update repo links

---

version.json

Waiting for the 25.05 channel to exist.

version: bump to 25.11

---

modules/module-list.nix
modules/programs/arqbackup.nix

I didn't add any tests as this is a proprietary package and the module is super simple

programs/arqbackup: init module

---

doc/known-files/27274e44b88a1174787f9a3d437d3387edc4f9aaaf40356054130797f5dc7912
doc/known-files/4d1ab5704f9d167a042fecac0d056c8a79a8ebd71e032d3489536c8db9ffe3e0
doc/known-files/bf76c5ed8e65e616f4329eccf662ee91be33b8bfd33713ce9946f2fe94fea7fa
doc/known-files/f320016e2cf13573731fbee34f9fe97ba867dd2a31f24893d3120154e9306e92
modules/programs/zsh/default.nix

etc: add known hashes for zprofile and zshrc in macOS 26 beta 1
